import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRightLeft, CheckCircle, ChevronDown, ChevronUp, Loader2, Scale, Shield, Trophy, Zap } from 'lucide-react';
import { purchaseQuotationsApi } from '../../api/quotationsApi';
import { formatCurrency } from '../../../../core/utils';
import { usePurchaseStore } from '../../store';
import { logger } from '../../../../core/utils/logger';

interface Props { rfqGroupId: string; onClose: () => void; onConvertToPurchase?: () => void; }
interface SupplierData { id: string; quotation_number: string; status: string; total_amount: number; delivery_terms: string | null; payment_terms: string | null; party: { id?: string; name: string } | null; quotation_items: QuotationItem[]; }
interface QuotationItem { id: string; product_id: string | null; description: string; quantity: number; unit_price: number; total: number; }
interface PriceRange { min: number; max: number; minSupplier: string; }
interface ComparisonResult { descriptions: string[]; priceMap: Map<string, PriceRange>; cheapestId: string; }
const asRecord = (value: unknown): Record<string, unknown> | null => typeof value === 'object' && value !== null ? value as Record<string, unknown> : null;
const asString = (value: unknown, fallback = ''): string => typeof value === 'string' ? value : fallback;
const asNumber = (value: unknown): number => typeof value === 'number' && Number.isFinite(value) ? value : 0;
const normalizeItem = (value: unknown): QuotationItem | null => { const row = asRecord(value); return row === null ? null : { id: asString(row.id), product_id: typeof row.product_id === 'string' ? row.product_id : null, description: asString(row.description), quantity: asNumber(row.quantity), unit_price: asNumber(row.unit_price), total: asNumber(row.total) }; };
const normalizeSupplier = (value: unknown): SupplierData | null => { const row = asRecord(value); if (row === null || asString(row.id) === '') return null; const party = asRecord(row.party); const items = Array.isArray(row.quotation_items) ? row.quotation_items.map(normalizeItem).filter((item): item is QuotationItem => item !== null) : []; return { id: asString(row.id), quotation_number: asString(row.quotation_number), status: asString(row.status), total_amount: asNumber(row.total_amount), delivery_terms: typeof row.delivery_terms === 'string' ? row.delivery_terms : null, payment_terms: typeof row.payment_terms === 'string' ? row.payment_terms : null, party: party === null ? null : { ...(typeof party.id === 'string' ? { id: party.id } : {}), name: asString(party.name, 'مورد غير محدد') }, quotation_items: items }; };
const normalizeSuppliers = (value: unknown): SupplierData[] => Array.isArray(value) ? value.map(normalizeSupplier).filter((supplier): supplier is SupplierData => supplier !== null) : [];
const buildComparison = (suppliers: SupplierData[]): ComparisonResult | null => { if (suppliers.length === 0) return null; const descriptions = [...new Set(suppliers.flatMap(supplier => supplier.quotation_items.map(item => item.description)))]; const priceMap = new Map<string, PriceRange>(); descriptions.forEach(description => { const prices = suppliers.flatMap(supplier => { const item = supplier.quotation_items.find(entry => entry.description === description); return item === undefined ? [] : [{ id: supplier.id, price: item.unit_price }]; }); const cheapest = prices.reduce((current, entry) => entry.price < current.price ? entry : current, prices[0]); priceMap.set(description, { min: Math.min(...prices.map(entry => entry.price)), max: Math.max(...prices.map(entry => entry.price)), minSupplier: cheapest.id }); }); const cheapestSupplier = suppliers.reduce((current, supplier) => supplier.total_amount < current.total_amount ? supplier : current, suppliers[0]); return { descriptions, priceMap, cheapestId: cheapestSupplier.id }; };

const ComparisonHeader = ({ suppliersCount, expanded, onToggle, onClose }: { suppliersCount: number; expanded: boolean; onToggle: () => void; onClose: () => void }): React.ReactElement => <div className="p-4 bg-gradient-to-r from-violet-50 to-indigo-50 dark:from-violet-900/20 dark:to-indigo-900/20 border-b border-violet-100 dark:border-violet-800/30 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-violet-600 flex items-center justify-center text-white shadow-lg shadow-violet-500/20"><Scale size={20} /></div><div><h3 className="font-bold text-gray-900 dark:text-white">مقارنة عروض الأسعار</h3><p className="text-xs text-violet-600 dark:text-violet-400 font-medium">{suppliersCount} عرض من {suppliersCount} مورد</p></div></div><div className="flex items-center gap-2"><button aria-label={expanded ? 'طي المقارنة' : 'توسيع المقارنة'} onClick={onToggle} className="p-2 text-gray-500 hover:text-violet-600 hover:bg-violet-50 dark:hover:bg-violet-900/20 rounded-lg transition-colors">{expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}</button><button onClick={onClose} className="px-3 py-1.5 text-xs text-gray-600 hover:text-gray-900 bg-gray-100 hover:bg-gray-200 dark:bg-slate-800 dark:hover:bg-slate-700 rounded-lg transition-colors">إغلاق</button></div></div>;
const PriceCell = ({ item, priceRange, supplierId }: { item: QuotationItem | undefined; priceRange: PriceRange | undefined; supplierId: string }): React.ReactElement => { if (item === undefined) return <span className="text-gray-300 dark:text-slate-600">—</span>; const isCheapest = priceRange?.minSupplier === supplierId; const isMostExpensive = priceRange?.max === item.unit_price && priceRange.max !== priceRange.min; const color = isCheapest ? 'text-emerald-600 dark:text-emerald-400' : isMostExpensive ? 'text-rose-500 dark:text-rose-400' : 'text-gray-800 dark:text-gray-200'; return <div className="flex flex-col items-center gap-0.5"><span className={`font-mono font-bold text-sm ${color}`} dir="ltr">{formatCurrency(item.unit_price)}</span>{isCheapest && <span className="text-[10px] text-emerald-500">الأقل</span>}<span className="text-[10px] text-gray-400">× {item.quantity}</span></div>; };
const ActionCell = ({ supplier, cheapestId, actionLoading, onConvert }: { supplier: SupplierData; cheapestId: string; actionLoading: string | null; onConvert: (id: string) => Promise<void> }): React.ReactElement => { if (supplier.status === 'converted') return <span className="flex items-center justify-center gap-1 text-xs font-bold text-indigo-600 dark:text-indigo-400"><CheckCircle size={14} /> تم التحويل</span>; return <button onClick={() => { void onConvert(supplier.id); }} disabled={actionLoading !== null} className={`flex items-center justify-center gap-1 mx-auto px-3 py-2 rounded-lg text-xs font-bold transition-all shadow-sm ${supplier.id === cheapestId ? 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-500/20' : 'bg-white dark:bg-slate-800 hover:bg-gray-100 dark:hover:bg-slate-700 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-slate-600'}`}>{actionLoading === supplier.id ? <Loader2 size={12} className="animate-spin" /> : <ArrowRightLeft size={12} />}{supplier.id === cheapestId ? 'اعتماد (موصى به)' : 'اعتماد'}</button>; };
const ComparisonTable = ({ suppliers, comparison, actionLoading, onConvert }: { suppliers: SupplierData[]; comparison: ComparisonResult; actionLoading: string | null; onConvert: (id: string) => Promise<void> }): React.ReactElement => <div className="overflow-x-auto scroll-x-hint-surface"><table className="w-full text-sm"><thead><tr className="border-b border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-800/50"><th className="text-right py-3 px-4 font-bold text-gray-700 dark:text-gray-300 text-xs sticky right-0 bg-gray-50 dark:bg-slate-800/50 z-10 min-w-[150px]">المنتج / البند</th>{suppliers.map(supplier => <th key={supplier.id} className="text-center py-3 px-4 font-bold text-xs min-w-[140px]"><div className="flex flex-col items-center gap-1"><span className={supplier.id === comparison.cheapestId ? 'text-emerald-600 dark:text-emerald-400' : 'text-gray-700 dark:text-gray-300'}>{supplier.party?.name ?? 'مورد غير محدد'}</span>{supplier.id === comparison.cheapestId && <span className="flex items-center gap-1 px-2 py-0.5 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 rounded-full text-[10px] font-bold"><Trophy size={10} /> الأوفر</span>}</div></th>)}</tr></thead><tbody>{comparison.descriptions.map(description => <tr key={description} className="border-b border-gray-50 dark:border-slate-800/50 hover:bg-gray-50 dark:hover:bg-slate-800/50 transition-colors"><td className="py-3 px-4 font-medium text-gray-800 dark:text-gray-200 sticky right-0 bg-[var(--app-surface)] z-10">{description}</td>{suppliers.map(supplier => <td key={supplier.id} className="py-3 px-4 text-center"><PriceCell item={supplier.quotation_items.find(item => item.description === description)} priceRange={comparison.priceMap.get(description)} supplierId={supplier.id} /></td>)}</tr>)}<SummaryRows suppliers={suppliers} comparison={comparison} /><tr className="bg-gradient-to-r from-violet-50 to-indigo-50 dark:from-violet-900/10 dark:to-indigo-900/10"><td className="py-4 px-4 font-bold text-violet-700 dark:text-violet-400 sticky right-0 bg-violet-50 dark:bg-violet-900/10 z-10">الإجراء</td>{suppliers.map(supplier => <td key={supplier.id} className="py-4 px-4 text-center"><ActionCell supplier={supplier} cheapestId={comparison.cheapestId} actionLoading={actionLoading} onConvert={onConvert} /></td>)}</tr></tbody></table></div>;
const SummaryRows = ({ suppliers, comparison }: { suppliers: SupplierData[]; comparison: ComparisonResult }): React.ReactElement => <><tr className="border-t-2 border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-800/30"><td className="py-3 px-4 font-bold text-gray-800 dark:text-gray-200 sticky right-0 bg-gray-50 dark:bg-slate-800/30 z-10">الإجمالي</td>{suppliers.map(supplier => <td key={supplier.id} className="py-3 px-4 text-center"><span className={`font-mono font-bold text-lg ${supplier.id === comparison.cheapestId ? 'text-emerald-600 dark:text-emerald-400' : 'text-gray-800 dark:text-gray-200'}`} dir="ltr">{formatCurrency(supplier.total_amount)}</span></td>)}</tr><tr className="bg-gray-50 dark:bg-slate-800/30"><td className="py-3 px-4 font-medium text-gray-600 dark:text-gray-400 sticky right-0 bg-gray-50 dark:bg-slate-800/30 z-10">شروط التسليم</td>{suppliers.map(supplier => <td key={supplier.id} className="py-3 px-4 text-center text-xs text-gray-600 dark:text-gray-400">{supplier.delivery_terms ?? '—'}</td>)}</tr><tr className="bg-gray-50 dark:bg-slate-800/30"><td className="py-3 px-4 font-medium text-gray-600 dark:text-gray-400 sticky right-0 bg-gray-50 dark:bg-slate-800/30 z-10">شروط الدفع</td>{suppliers.map(supplier => <td key={supplier.id} className="py-3 px-4 text-center text-xs text-gray-600 dark:text-gray-400">{supplier.payment_terms ?? '—'}</td>)}</tr></>;
const RecommendationsBar = ({ suppliers, cheapestId }: { suppliers: SupplierData[]; cheapestId: string }): React.ReactElement => { const totals = suppliers.map(supplier => supplier.total_amount); const cheapest = suppliers.find(supplier => supplier.id === cheapestId); const difference = suppliers.length >= 2 ? Math.max(...totals) - Math.min(...totals) : null; return <div className="p-4 border-t border-gray-100 dark:border-slate-800 bg-gradient-to-r from-emerald-50 to-teal-50 dark:from-emerald-900/10 dark:to-teal-900/10"><div className="flex flex-wrap items-center gap-4">{cheapest !== undefined && <div className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-slate-800/80 rounded-xl border border-emerald-200 dark:border-emerald-800/30 shadow-sm"><Trophy size={16} className="text-emerald-600" /><span className="text-xs font-bold text-emerald-700 dark:text-emerald-400">الأوفر إجمالياً:</span><span className="text-xs font-medium text-gray-700 dark:text-gray-300">{cheapest.party?.name ?? 'مورد غير محدد'}</span></div>}<div className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-slate-800/80 rounded-xl border border-blue-200 dark:border-blue-800/30 shadow-sm"><Zap size={16} className="text-blue-600" /><span className="text-xs font-bold text-blue-700 dark:text-blue-400">عدد العروض:</span><span className="text-xs font-medium text-gray-700 dark:text-gray-300">{suppliers.length}</span></div><div className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-slate-800/80 rounded-xl border border-violet-200 dark:border-violet-800/30 shadow-sm"><Shield size={16} className="text-violet-600" /><span className="text-xs font-bold text-violet-700 dark:text-violet-400">فارق السعر:</span><span className="text-xs font-medium text-gray-700 dark:text-gray-300" dir="ltr">{difference === null ? '—' : formatCurrency(difference)}</span></div></div></div>; };

const QuotationComparisonView: React.FC<Props> = ({ rfqGroupId, onClose, onConvertToPurchase }) => {
  const [suppliers, setSuppliers] = useState<SupplierData[]>([]); const [loading, setLoading] = useState(true); const [actionLoading, setActionLoading] = useState<string | null>(null); const [expanded, setExpanded] = useState(true);
  const fetchComparison = useCallback(async (): Promise<void> => { if (rfqGroupId === '') return; setLoading(true); try { const response = await purchaseQuotationsApi.getComparisonData(rfqGroupId); const rawData: unknown = response.data; setSuppliers(normalizeSuppliers(rawData)); } finally { setLoading(false); } }, [rfqGroupId]);
  useEffect(() => { void fetchComparison(); }, [fetchComparison]);
  const comparison = useMemo(() => buildComparison(suppliers), [suppliers]);
  const handleConvertToPurchase = async (quotationId: string): Promise<void> => { const quotation = suppliers.find(supplier => supplier.id === quotationId); if (quotation === undefined) return; setActionLoading(quotationId); try { const { resetCart, setSupplier, bulkLoadItems } = usePurchaseStore.getState(); resetCart(); if (quotation.party !== null) setSupplier({ id: quotation.party.id ?? 'temp', name: quotation.party.name }); if (quotation.quotation_items.length > 0) bulkLoadItems(quotation.quotation_items.map(item => ({ productId: item.product_id ?? '', name: item.description, quantity: item.quantity, unitPrice: item.unit_price, costPrice: item.unit_price }))); await purchaseQuotationsApi.updateStatus(quotationId, 'converted'); onClose(); if (onConvertToPurchase !== undefined) onConvertToPurchase(); } catch (error) { logger.error("QuotationComparisonView", 'Failed to convert purchase quotation:', error); } finally { setActionLoading(null); } };
  if (loading) return <div className="flex items-center justify-center py-16"><Loader2 className="w-6 h-6 animate-spin text-indigo-500" /></div>;
  if (comparison === null) return <div className="text-center py-12 bg-gray-50 dark:bg-slate-800/50 rounded-2xl border border-gray-100 dark:border-slate-700"><Scale size={40} className="mx-auto text-gray-300 dark:text-slate-600 mb-3" /><p className="text-gray-500 dark:text-gray-400 font-medium">لا توجد عروض للمقارنة</p></div>;
  return <div className="bg-[var(--app-surface)] rounded-2xl border border-gray-100 dark:border-slate-800 shadow-sm overflow-hidden"><ComparisonHeader suppliersCount={suppliers.length} expanded={expanded} onToggle={() => { setExpanded(value => !value); }} onClose={onClose} />{expanded && <><ComparisonTable suppliers={suppliers} comparison={comparison} actionLoading={actionLoading} onConvert={handleConvertToPurchase} /><RecommendationsBar suppliers={suppliers} cheapestId={comparison.cheapestId} /></>}</div>;
};
export default QuotationComparisonView;
