#!/usr/bin/env tsx
/**
 * Compress Theme Presets
 * Removes redundant `cssVars` blocks that exactly duplicate `light` or `dark`,
 * and rewrites the file using a `normalize()` helper so behavior stays identical.
 *
 * Usage: npx tsx scripts/compress-themes.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import type { ThemePreset } from '../src/features/appearance/types';

const SRC = path.join(process.cwd(), 'src', 'features', 'appearance', 'constants.ts');

async function main() {
  // Import the live data from the current file (safe: it is valid TS).
  const mod = await import('../src/features/appearance/constants.ts');
  const presets: ThemePreset[] = mod.THEME_PRESETS;
  const categories = mod.THEME_CATEGORIES;

  if (!Array.isArray(presets) || presets.length === 0) {
    throw new Error('Could not load THEME_PRESETS from constants.ts');
  }

  const isDeepEqual = (a: unknown, b: unknown): boolean =>
    JSON.stringify(a) === JSON.stringify(b);

  interface OutputTheme {
    keyValues: Array<[string, unknown]>;
    droppedCssVars: boolean;
  }

  const outputs: OutputTheme[] = presets.map((p) => {
    const entries = Object.entries(p) as Array<[string, unknown]>;
    const hasDualModes = !!(p.light && p.dark);

    // For dual-mode (pro) themes cssVars is not used at runtime; drop it only
    // when it exactly duplicates the value `normalize()` would regenerate.
    let droppedCssVars = false;
    let entriesOut = entries;
    if (hasDualModes && p.cssVars) {
      const expected = p.isDark ? p.dark : p.light;
      if (isDeepEqual(p.cssVars, expected)) {
        entriesOut = entries.filter(([k]) => k !== 'cssVars');
        droppedCssVars = true;
      }
    }

    return { keyValues: entriesOut, droppedCssVars };
  });

  // ── Pretty printing helpers ──────────────────────────────────────────────

  const printValue = (v: unknown, indent: number): string => {
    const pad = ' '.repeat(indent);
    if (v === null) return 'null';
    if (Array.isArray(v)) {
      const inner = v.map((x) => JSON.stringify(x)).join(', ');
      return `[${inner}]`;
    }
    if (typeof v === 'object') {
      const obj = v as Record<string, unknown>;
      const keys = Object.keys(obj);
      if (keys.length === 0) return '{}';
      const body = keys
        .map((k) => `${pad}  ${printKey(k)}: ${printValue(obj[k], indent + 2)},`)
        .join('\n');
      return `{\n${body}\n${pad}}`;
    }
    return JSON.stringify(v);
  };

  const printKey = (k: string): string => (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

  const printTheme = (o: OutputTheme): string => {
    const lines = o.keyValues.map(([k, v]) => {
      if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
        const inner = (Object.keys(v as Record<string, unknown>) as string[])
          .map((ik) => `      ${printKey(ik)}: ${printValue((v as Record<string, unknown>)[ik], 6)},`)
          .join('\n');
        return `    ${printKey(k)}: {\n${inner}\n    },`;
      }
      return `    ${printKey(k)}: ${printValue(v, 4)},`;
    });
    return `  normalize({\n${lines.join('\n')}\n  }),`;
  };

  // ── Group themes by category with readable separators ────────────────────

  const CATEGORY_LABELS: Record<string, string> = {
    premium: 'باقات برو الاحترافية — Premium Pro',
    classic: 'كلاسيكي — Classic',
    beige: 'بيج — Beige & Warm Tones',
    royal: 'ملكي — Royal & Luxury',
    accounting: 'محاسبي — Accounting & Finance',
    nature: 'طبيعي — Nature',
    bold: 'جريء — Bold',
    corporate: 'شركة — Corporate & Modern',
    night: 'ليلي — Night Themes',
    seasonal: 'موسمي — Seasonal',
    artistic: 'فني — Artistic',
    industry: 'قطاعي — Industry',
    glass: 'زجاجي — Glass',
    bento: 'بينتو — Bento',
    automotive: 'قطع غيار — Automotive',
  };

  const withGroupComments = (items: OutputTheme[]): string => {
    let lastCategory: string | null = null;
    const parts: string[] = [];
    items.forEach((o, idx) => {
      const theme = presets[idx];
      const cat = (theme.category as string) ?? 'premium';
      if (cat !== lastCategory) {
        const label = CATEGORY_LABELS[cat] ?? cat;
        const sep = '═'.repeat(70);
        parts.push(`  // ${sep}`);
        parts.push(`  // ${label}`);
        parts.push(`  // ${sep}`);
        lastCategory = cat;
      }
      parts.push(printTheme(o));
    });
    return parts.join('\n');
  };

  // ── Build the new file ───────────────────────────────────────────────────

  const header = `// ═══════════════════════════════════════════════════════════════
// 🎨 Theme Presets — Al-Zahra Smart ERP
// ═══════════════════════════════════════════════════════════════
// Generated by scripts/compress-themes.ts (do not edit by hand).
//
// Each preset keeps only its unique data. Dual-mode presets drop the
// cssVars block when it duplicates light/dark; normalize() restores
// it at runtime so downstream consumers (themeStore etc.) keep working.
// ═══════════════════════════════════════════════════════════════

import type { ThemeCSSVars, ThemePreset } from './types';

type RawTheme = Omit<ThemePreset, 'cssVars'> & { cssVars?: ThemeCSSVars };

/**
 * Restores the required cssVars field for compact dual-mode presets.
 * For legacy single-mode themes the explicit cssVars is always kept.
 */
const normalize = (theme: RawTheme): ThemePreset => ({
  ...theme,
  cssVars: theme.cssVars ?? (theme.isDark ? theme.dark! : theme.light!),
});

export const THEME_PRESETS: ThemePreset[] = [
`;

  const categoriesBlock = `
// تصنيفات الثيمات مع الأسماء العربية
export const THEME_CATEGORIES = ${JSON.stringify(categories, null, 2).replace(/"/g, "'")} as const;
`;

  const newFile =
    header + withGroupComments(outputs) + '\n];\n' + categoriesBlock;

  fs.writeFileSync(SRC, newFile, 'utf-8');

  const dropped = outputs.filter((o) => o.droppedCssVars).length;
  console.log(`✅ Rewrote ${SRC}`);
  console.log(`   Themes: ${presets.length}`);
  console.log(`   cssVars blocks dropped: ${dropped}`);
  console.log(`   New size: ${(newFile.length / 1024).toFixed(1)} KB`);
}

main().catch((err) => {
  console.error('❌ Failed:', err);
  process.exit(1);
});
