
export const ROUTES = {
  AUTH: {
    LANDING: '/welcome',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    UPDATE_PASSWORD: '/update-password',
  },
  DASHBOARD: {
    ROOT: '/',
    INVENTORY: '/inventory',
    INVENTORY_AUDIT_SESSION: '/inventory/audit/:sessionId',
    INVENTORY_QUICK_AUDIT: '/inventory/quick-audit',
    ACCOUNTING: '/accounting',
    SALES: '/sales',
    PURCHASES: '/purchases',
    POS: '/pos',
    EXPENSES: '/expenses',
    SETTINGS: '/settings',
    APPEARANCE: '/settings/appearance',
    BONDS: '/bonds',
    SUPPLIERS: '/suppliers',
    CLIENTS: '/clients',
    PARTIES: '/parties',
    PARTIES_CUSTOMERS: '/parties/customers',
    PARTIES_SUPPLIERS: '/parties/suppliers',
    REPORTS: '/reports',
    AI: '/ai',
    VIN_INTELLIGENCE: '/vin-intelligence',
    DEBTS: '/debts',
    DEBTS_FOLLOW_UP: '/debts/follow-up',
    DEBTS_TODAY: '/debts/today',
    DEBTS_CUSTOMER: '/debts/customer/:id',
    DEBTS_OUTBOX: '/debts/outbox',
    DEBTS_REPORTS: '/debts/reports',
    DEBTS_SETTINGS: '/debts/settings',
  },
} as const;

export type AppRoute = string;