import React from 'react';
import { BookOpen } from 'lucide-react';
import { cn, formatCurrency } from '../../../core/utils';
import type { BondType } from '../types';

interface PartyLike {
  name?: string | null;
}
interface AccountLike {
  name?: string | null;
}

interface BondJournalPreviewProps {
  type: BondType;
  enteredAmount: number;
  commissionAmount: number;
  selectedCurrency: string;
  selectedCashAccount: AccountLike | null | undefined;
  selectedCounterpartyAccount: AccountLike | null | undefined;
  selectedParty: PartyLike | null | undefined;
  selectedCommissionAccount: AccountLike | null | undefined;
}

const FALLBACK_DEBIT: Record<BondType, string> = {
  receipt: 'حساب الصندوق / البنك',
  payment: 'حساب المورد / المصروف',
  transfer: 'حساب الخزينة المحول إليها',
};
const FALLBACK_CREDIT: Record<BondType, string> = {
  receipt: 'حساب العميل',
  payment: 'حساب الصندوق / البنك',
  transfer: 'حساب الخزينة المحول منها',
};

/** Resolve the debit account display name by bond type. */
const resolveDebitName = (p: BondJournalPreviewProps): string => {
  const candidates: Record<BondType, string | null | undefined> = {
    receipt: p.selectedCashAccount?.name,
    payment: p.selectedParty?.name ?? p.selectedCounterpartyAccount?.name,
    transfer: p.selectedCounterpartyAccount?.name,
  };
  return candidates[p.type] ?? FALLBACK_DEBIT[p.type];
};

/** Resolve the credit account display name by bond type. */
const resolveCreditName = (p: BondJournalPreviewProps): string => {
  const candidates: Record<BondType, string | null | undefined> = {
    receipt: p.selectedParty?.name ?? p.selectedCounterpartyAccount?.name,
    payment: p.selectedCashAccount?.name,
    transfer: p.selectedCashAccount?.name,
  };
  return candidates[p.type] ?? FALLBACK_CREDIT[p.type];
};

interface JournalRowProps {
  side: 'مدين' | 'دائن';
  name: string;
  amount: number;
  currency: string;
  tone: 'emerald' | 'rose' | 'amber';
}

const TONE_PALETTES = {
  emerald: {
    wrap: 'border-emerald-100/60 bg-emerald-50/60 dark:border-emerald-900/30 dark:bg-emerald-950/20',
    badge: 'bg-emerald-600',
    amount: 'text-emerald-700 dark:text-emerald-400',
  },
  rose: {
    wrap: 'border-rose-100/60 bg-rose-50/60 dark:border-rose-900/30 dark:bg-rose-950/20',
    badge: 'bg-rose-600',
    amount: 'text-rose-700 dark:text-rose-400',
  },
  amber: {
    wrap: 'border-amber-100/60 bg-amber-50/60 dark:border-amber-900/30 dark:bg-amber-950/20',
    badge: 'bg-amber-600',
    amount: 'text-amber-700 dark:text-amber-400',
  },
} as const;

const JournalRow: React.FC<JournalRowProps> = ({ side, name, amount, currency, tone }) => {
  // eslint-disable-next-line security/detect-object-injection -- tone is a closed union key of TONE_PALETTES
  const palette = TONE_PALETTES[tone];

  return (
    <div className={cn('flex items-center justify-between rounded-xl border p-2.5', palette.wrap)}>
      <div className="flex items-center gap-2">
        <span
          className={cn('rounded-md px-2 py-0.5 text-[10px] font-black text-white', palette.badge)}
        >
          {side}
        </span>
        <span className="font-bold text-slate-800 dark:text-slate-200">{name}</span>
      </div>
      <span className={cn('font-mono font-bold', palette.amount)}>
        {formatCurrency(amount, currency)}
      </span>
    </div>
  );
};

/** Live preview of the accounting journal entry generated by the bond. */
// eslint-disable-next-line max-lines-per-function -- presentation card composing journal rows; splitting adds prop-drilling indirection.
export const BondJournalPreview: React.FC<BondJournalPreviewProps> = props => {
  const { type, enteredAmount, commissionAmount, selectedCurrency } = props;
  const hasCommission = type === 'receipt' && commissionAmount > 0;

  return (
    <div className="space-y-3 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:rounded-3xl sm:p-5">
      <div className="flex items-center justify-between border-b border-slate-100 pb-2.5 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <div className="rounded-lg bg-blue-50 p-1.5 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400">
            <BookOpen size={16} />
          </div>
          <div>
            <h4 className="text-xs font-black text-slate-900 dark:text-white">
              محاكي القيد المحاسبي المتولد
            </h4>
            <p className="text-[10px] text-slate-400">
              معاينة حركة الحسابات الآلية الناتجة عن السند
            </p>
          </div>
        </div>
        <span className="rounded-full bg-slate-100 px-2.5 py-0.5 text-[10px] font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-400">
          مباشر (Live)
        </span>
      </div>

      <div className="space-y-2 text-xs">
        <JournalRow
          side="مدين"
          name={resolveDebitName(props)}
          amount={enteredAmount}
          currency={selectedCurrency}
          tone="emerald"
        />

        {hasCommission && (
          <JournalRow
            side="مدين"
            name={props.selectedCommissionAccount?.name ?? 'خصم مسموح به'}
            amount={commissionAmount}
            currency={selectedCurrency}
            tone="amber"
          />
        )}

        <JournalRow
          side="دائن"
          name={resolveCreditName(props)}
          amount={hasCommission ? enteredAmount + commissionAmount : enteredAmount}
          currency={selectedCurrency}
          tone="rose"
        />
      </div>
    </div>
  );
};

export default BondJournalPreview;
