import React from 'react';
import { CircleAlert, ShieldCheck, Users } from 'lucide-react';
import type { CommissionPeriod } from '../types';
import { formatCommissionDate, formatCommissionMoney, periodStateLabels } from './commissionLabels';
import type { useCommissionDashboardData } from './useCommissionDashboardData';

type DashboardData = ReturnType<typeof useCommissionDashboardData>;

export function Metric({ title, value, icon, tone }: { title: string; value: string; icon: React.ReactNode; tone: 'emerald' | 'blue' | 'violet' | 'amber' }): React.JSX.Element {
  const color = tone === 'emerald' ? 'bg-emerald-50 text-emerald-700' : tone === 'blue' ? 'bg-blue-50 text-blue-700' : tone === 'violet' ? 'bg-violet-50 text-violet-700' : 'bg-amber-50 text-amber-700';
  return <div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] p-4 shadow-sm"><div className={`mb-3 flex h-9 w-9 items-center justify-center rounded-lg ${color}`}>{icon}</div><p className="text-xs text-[var(--app-text-secondary)]">{title}</p><p className="mt-1 truncate text-lg font-bold text-[var(--app-text)]">{value}</p></div>;
}

export function PeriodResults({ data }: { data: DashboardData }): React.JSX.Element {
  return <div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] shadow-sm"><div className="flex flex-col gap-3 border-b border-[var(--app-border)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-[var(--app-text)]">نتائج الفترة</h2><p className="text-xs text-[var(--app-text-secondary)]">يتم عرض المهندسين الذين لديهم assignment صالح وروابط فواتير معتمدة.</p></div><select className="rounded-lg border border-[var(--app-border)] bg-[var(--app-bg)] px-3 py-2 text-sm text-[var(--app-text)]" value={data.selectedPeriod?.id ?? ''} onChange={event => { data.setSelectedPeriodId(event.target.value); }}>{data.periods.map((period: CommissionPeriod) => <option key={period.id} value={period.id}>{period.period_label} — {periodStateLabels[period.state]}{period.is_test_period ? ' (اختبار)' : ''}</option>)}</select></div><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-sm"><thead><tr className="border-b border-[var(--app-border)] text-right text-xs text-[var(--app-text-secondary)]"><th className="p-4">المهندس</th><th className="p-4">المبيعات</th><th className="p-4">المحصل</th><th className="p-4">الفواتير</th><th className="p-4">الإجمالي</th></tr></thead><tbody>{data.calculations.map(item => <tr key={item.id} className="border-b border-[var(--app-border)] last:border-0"><td className="p-4 font-medium text-[var(--app-text)]"><span className="inline-flex items-center gap-2"><Users size={15} className="text-emerald-600" />{item.user_id.slice(0, 8)}…</span></td><td className="p-4 text-[var(--app-text-secondary)]">{formatCommissionMoney(item.net_sales, item.currency_code)}</td><td className="p-4 text-[var(--app-text-secondary)]">{formatCommissionMoney(item.collected_amount, item.currency_code)}</td><td className="p-4 text-[var(--app-text-secondary)]">{item.invoice_count.toLocaleString('ar-SA')}</td><td className="p-4 font-semibold text-emerald-700">{formatCommissionMoney(item.total_commission, item.currency_code)}</td></tr>)}{data.calculations.length === 0 && <tr><td colSpan={5} className="p-10 text-center text-sm text-[var(--app-text-secondary)]">لا توجد حسابات لهذه الفترة بعد.</td></tr>}</tbody></table></div></div>;
}

export function DashboardAlerts({ data }: { data: DashboardData }): React.JSX.Element {
  return <>{data.hasError && <div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><CircleAlert size={17} /> تعذر تنفيذ العملية. تحقّق من الصلاحيات وحالة الفترة ثم أعد المحاولة.</div>}{data.selectedPeriod?.is_test_period === true && <div className="flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><ShieldCheck size={17} /> هذه فترة اختبار. سيُسمح بالحساب والمراجعة فقط، وتبقى عمليات القفل والدفع والترحيل محمية على مستوى قاعدة البيانات.</div>}</>;
}

export function PendingInvoices({ data }: { data: DashboardData }): React.JSX.Element {
  return <aside className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] shadow-sm"><div className="border-b border-[var(--app-border)] p-4"><h2 className="font-semibold text-[var(--app-text)]">قائمة الفواتير المعلقة</h2><p className="mt-1 text-xs text-[var(--app-text-secondary)]">فواتير مؤهلة بلا توزيع مهندس نشط.</p></div><div className="max-h-[440px] space-y-2 overflow-y-auto p-3">{data.pending.map(item => <div key={item.id} className="rounded-lg border border-amber-100 bg-amber-50/60 p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium text-[var(--app-text)]">فاتورة {item.invoice_id.slice(0, 8)}…</span><span className="text-[11px] text-amber-700">{item.status === 'pending' ? 'معلقة' : 'موزعة'}</span></div><p className="mt-1 text-xs text-[var(--app-text-secondary)]">اكتشفت في {formatCommissionDate(item.detected_at)}</p></div>)}{data.pending.length === 0 && <p className="p-6 text-center text-sm text-[var(--app-text-secondary)]">لا توجد فواتير معلقة.</p>}</div></aside>;
}
