import React from 'react';
import { useCommissionAssignmentsController } from './useCommissionAssignmentsController';
import { AssignmentField, AssignmentNotice, AssignmentSubmitIcon, PendingInvoiceList } from './CommissionAssignmentComponents';

export default function CommissionAssignmentsPage(): React.JSX.Element {
  const controller = useCommissionAssignmentsController();
  if (!controller.hasCompany) return <div dir="rtl" className="p-6 text-[var(--app-text-secondary)]">لا يمكن تحميل قائمة الانتظار قبل تحديد الشركة.</div>;
  return <div dir="rtl" className="min-h-full space-y-6 bg-[var(--app-bg)] p-4 sm:p-6"><header><p className="text-sm text-[var(--app-text-secondary)]">الحوافز / التوزيعات</p><h1 className="mt-1 text-2xl font-bold text-[var(--app-text)]">قائمة انتظار تعيين المهندسين</h1><p className="mt-2 max-w-3xl text-sm text-[var(--app-text-secondary)]">لا يتم احتساب أي فاتورة بلا assignment صالح. جميع الروابط تمر عبر RPC ذري يرفض النسب غير المكتملة أو المتجاوزة.</p></header><AssignmentNotice /><section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><PendingInvoiceList items={controller.pendingItems} selectedId={controller.selected} onSelect={item => { controller.selectInvoice(item.invoice_id, item.id); }} onIgnore={controller.ignoreInvoice} isIgnoring={controller.isIgnoring} /><aside className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] p-4 shadow-sm"><h2 className="font-semibold text-[var(--app-text)]">تعيين آمن</h2><p className="mt-1 text-xs text-[var(--app-text-secondary)]">يجب أن يكون مجموع النسب 100٪ داخل العملية نفسها.</p><div className="mt-4 space-y-3"><AssignmentField label="معرّف الفاتورة" value={controller.invoiceId} onChange={controller.setInvoiceId} disabled /><AssignmentField label="معرّف المهندس" value={controller.engineerId} onChange={controller.setEngineerId} placeholder="UUID" /><AssignmentField label="نسبة التوزيع" value={controller.allocation} onChange={controller.setAllocation} type="number" /><label className="block text-xs text-[var(--app-text-secondary)]">سبب التعيين التاريخي (اختياري)<textarea className="mt-1 min-h-20 w-full rounded-lg border border-[var(--app-border)] bg-[var(--app-bg)] p-2 text-sm" value={controller.reason} onChange={event => { controller.setReason(event.target.value); }} /></label></div><button type="button" className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" onClick={controller.submit} disabled={!controller.canSubmit}><AssignmentSubmitIcon historical={controller.reason.trim().length > 0} pending={controller.linkPending} />{controller.reason.trim().length > 0 ? 'حفظ تعيين تاريخي' : 'حفظ التعيين'}</button>{controller.linkError && <p className="mt-3 text-xs text-red-700">تعذر الحفظ؛ تحقق من الصلاحيات ومن اكتمال نسبة التوزيع إلى 100٪.</p>}</aside></section></div>;
}
