import React from 'react';
import { CheckCircle2, Plus, SlidersHorizontal } from 'lucide-react';
import type { CommissionPlan } from '../types';
import type { useCommissionConfigurationData } from './useCommissionConfigurationData';
import { calculationMethodLabels, formatCommissionNumber, planBasisLabels } from './commissionLabels';

type ConfigurationModel = ReturnType<typeof useCommissionConfigurationData>;

export function PlanForm(props: ConfigurationModel): React.JSX.Element {
  return <div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] p-2 max-md:rounded-lg shadow-sm sm:p-4"><h2 className="mb-2 flex items-center gap-1.5 font-semibold sm:mb-4 sm:gap-2 text-[var(--app-text)]"><Plus size={17} /> إنشاء خطة</h2><div className="space-y-2 max-md:space-y-1.5 sm:space-y-3"><label className="block text-sm text-[var(--app-text-secondary)]">اسم الخطة<input value={props.name} onChange={event => { props.setName(event.target.value); }} className="mt-0.5 w-full rounded-lg border border-[var(--app-border)] bg-[var(--app-bg)] px-2 py-1.5 max-md:px-1.5 max-md:py-1 text-[var(--app-text)] sm:mt-1 sm:px-3 sm:py-2" placeholder="مثال: عمولات المبيعات 2026" /></label><label className="block text-sm text-[var(--app-text-secondary)]">أساس الحساب<select value={props.basis} onChange={event => { props.setBasis(event.target.value as CommissionPlan['calculation_basis']); }} className="mt-0.5 w-full rounded-lg border border-[var(--app-border)] bg-[var(--app-bg)] px-2 py-1.5 max-md:px-1.5 max-md:py-1 text-[var(--app-text)] sm:mt-1 sm:px-3 sm:py-2">{Object.entries(planBasisLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="block text-sm text-[var(--app-text-secondary)]">العملة<input value={props.currency} onChange={event => { props.setCurrency(event.target.value.toUpperCase()); }} maxLength={3} className="mt-1 w-full rounded-lg border border-[var(--app-border)] bg-[var(--app-bg)] px-3 py-2 uppercase text-[var(--app-text)]" /></label><button type="button" disabled={props.name.trim().length === 0 || props.creating} onClick={props.create} className="w-full rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{props.creating ? 'جارٍ الحفظ…' : 'حفظ الخطة'}</button>{props.createError && <p className="text-xs text-rose-700">تعذر إنشاء الخطة. تحقق من الاسم والصلاحيات.</p>}</div></div>;
}

export function PlanList(props: ConfigurationModel): React.JSX.Element {
  return <div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] shadow-sm"><div className="flex flex-wrap items-center justify-between gap-1.5 border-b border-[var(--app-border)] p-2 max-md:gap-1 sm:gap-3 sm:p-4"><div><h2 className="font-semibold text-[var(--app-text)]">الخطط الحالية</h2><p className="text-xs text-[var(--app-text-secondary)]">{formatCommissionNumber(props.plans.length)} خطة غير محذوفة</p></div>{props.selected && <button type="button" disabled={props.toggling} onClick={props.toggleActive} className="inline-flex items-center gap-2 rounded-lg border border-emerald-200 px-3 py-2 text-sm text-emerald-700"><CheckCircle2 size={16} />{props.selected.status === 'active' ? 'تعطيل الخطة' : 'تفعيل الخطة'}</button>}</div><div className="divide-y divide-[var(--app-border)]">{props.plans.map(plan => <button type="button" key={plan.id} onClick={() => { props.setSelectedId(plan.id); }} className={`block w-full p-2 max-md:p-1.5 text-right transition-colors sm:p-4 ${props.selected?.id === plan.id ? 'bg-emerald-50/70' : 'hover:bg-[var(--app-bg)]'}`}><div className="flex items-center justify-between gap-3"><span className="font-semibold text-[var(--app-text)]">{plan.name}</span><span className={`rounded-full px-2 py-1 text-[11px] ${plan.status === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{plan.status === 'active' ? 'نشطة' : plan.status === 'draft' ? 'مسودة' : 'غير نشطة'}</span></div><p className="mt-1 text-xs text-[var(--app-text-secondary)]">الأساس: {planBasisLabels[plan.calculation_basis]} · العملة: {plan.currency_code}</p></button>)}{props.plans.length === 0 && <div className="p-10 text-center text-sm text-[var(--app-text-secondary)]">لا توجد خطط بعد.</div>}</div></div>;
}

export function PlanDetails(props: ConfigurationModel): React.JSX.Element | null {
  if (!props.selected) return null;
  return <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] p-2 max-md:rounded-lg shadow-sm sm:p-4"><h2 className="flex items-center gap-2 font-semibold text-[var(--app-text)]"><SlidersHorizontal size={17} /> قواعد الخطة</h2><div className="mt-2 space-y-1.5 max-md:mt-1 sm:mt-4 sm:space-y-2">{props.rules.map(rule => <div key={rule.id} className="rounded-lg border border-[var(--app-border)] p-3"><div className="flex justify-between gap-2"><span className="text-sm font-medium text-[var(--app-text)]">{rule.name}</span><span className="text-xs text-[var(--app-text-secondary)]">{calculationMethodLabels[rule.calculation_method]}</span></div><p className="mt-1 text-xs text-[var(--app-text-secondary)]">الأولوية {formatCommissionNumber(rule.priority)} · {rule.is_active ? 'فعالة' : 'متوقفة'}</p></div>)}{props.rules.length === 0 && <p className="py-6 text-sm text-[var(--app-text-secondary)]">لا توجد قواعد معرفة لهذه الخطة.</p>}</div></div><div className="rounded-xl border border-[var(--app-border)] bg-[var(--app-card)] p-2 max-md:rounded-lg shadow-sm sm:p-4"><h2 className="font-semibold text-[var(--app-text)]">شرائح الحساب</h2><div className="mt-2 space-y-1.5 max-md:mt-1 sm:mt-4 sm:space-y-2">{props.tiers.map(tier => <div key={tier.id} className="flex items-center justify-between rounded-lg border border-[var(--app-border)] p-3 text-sm"><span className="text-[var(--app-text)]">{formatCommissionNumber(tier.from_amount)} – {tier.to_amount == null ? '∞' : formatCommissionNumber(tier.to_amount)} {tier.tier_currency_code}</span><span className="font-semibold text-emerald-700">{tier.rate != null ? `${formatCommissionNumber(tier.rate)}%` : formatCommissionNumber(tier.fixed_bonus)}</span></div>)}{props.tiers.length === 0 && <p className="py-6 text-sm text-[var(--app-text-secondary)]">لا توجد شرائح معرفة لهذه الخطة.</p>}</div></div></section>;
}
