-- ============================================================
-- SEED (GAP): role_permissions matrix
-- ------------------------------------------------------------
-- The permission matrix exists ONLY as live data (0 INSERT
-- statements in the repo migrations). A fresh environment built
-- from the repo would start with an EMPTY matrix and
-- has_permission() would deny everything.
-- This migration snapshots the current live matrix (108 rows,
-- 9 roles) idempotently. Date: 2026-08-21
-- ============================================================

INSERT INTO public.role_permissions (role, permission)
SELECT v.role, v.permission
FROM (VALUES
        ('accountant', 'sales:read'),
        ('accountant', 'sales:update'),
        ('accountant', 'purchases:read'),
        ('accountant', 'accounting:create'),
        ('accountant', 'accounting:read'),
        ('accountant', 'accounting:update'),
        ('accountant', 'expenses:create'),
        ('accountant', 'expenses:read'),
        ('accountant', 'expenses:update'),
        ('accountant', 'reports:read'),
        ('accountant', 'reports:export'),
        ('accountant', 'debts:read'),
        ('accountant', 'debts:manage'),
        ('accountant', 'commission:view'),
        ('accountant', 'commission:record_payment'),
        ('accountant', 'commission:reports'),
        ('admin', 'sales:create'),
        ('admin', 'sales:read'),
        ('admin', 'sales:update'),
        ('admin', 'sales:delete'),
        ('admin', 'purchases:create'),
        ('admin', 'purchases:read'),
        ('admin', 'purchases:update'),
        ('admin', 'purchases:delete'),
        ('admin', 'accounting:create'),
        ('admin', 'accounting:read'),
        ('admin', 'accounting:update'),
        ('admin', 'accounting:delete'),
        ('admin', 'inventory:create'),
        ('admin', 'inventory:read'),
        ('admin', 'inventory:update'),
        ('admin', 'inventory:delete'),
        ('admin', 'customers:create'),
        ('admin', 'customers:read'),
        ('admin', 'customers:update'),
        ('admin', 'customers:delete'),
        ('admin', 'expenses:create'),
        ('admin', 'expenses:read'),
        ('admin', 'expenses:update'),
        ('admin', 'expenses:delete'),
        ('admin', 'reports:read'),
        ('admin', 'reports:export'),
        ('admin', 'ai:use'),
        ('admin', 'admin:access'),
        ('admin', 'settings:manage'),
        ('admin', 'debts:read'),
        ('admin', 'debts:manage'),
        ('admin', 'debts:remind'),
        ('branch_manager', 'commission:view_branch'),
        ('branch_manager', 'incentive:assign_branch'),
        ('branch_manager', 'incentive:view_targets'),
        ('branch_manager', 'incentive:manage_pending_branch'),
        ('engineer', 'commission:view_own'),
        ('engineer', 'incentive:view_own_targets'),
        ('engineer', 'incentive:view_own_payments'),
        ('finance_manager', 'commission:calculate'),
        ('finance_manager', 'commission:review'),
        ('finance_manager', 'commission:approve'),
        ('finance_manager', 'commission:pay'),
        ('finance_manager', 'commission:reports'),
        ('finance_manager', 'incentive:manage_plans'),
        ('finance_manager', 'incentive:manage_assignments'),
        ('finance_manager', 'incentive:manage_targets'),
        ('finance_manager', 'incentive:manage_periods'),
        ('finance_manager', 'incentive:manage_pending'),
        ('hr', 'incentive:manage_assignments'),
        ('hr', 'incentive:manage_targets'),
        ('hr', 'incentive:manage_plans'),
        ('hr', 'incentive:view_performance'),
        ('hr', 'incentive:manage_pending'),
        ('hr', 'commission:view'),
        ('manager', 'sales:create'),
        ('manager', 'sales:read'),
        ('manager', 'sales:update'),
        ('manager', 'purchases:create'),
        ('manager', 'purchases:read'),
        ('manager', 'purchases:update'),
        ('manager', 'accounting:create'),
        ('manager', 'accounting:read'),
        ('manager', 'accounting:update'),
        ('manager', 'inventory:read'),
        ('manager', 'inventory:update'),
        ('manager', 'customers:create'),
        ('manager', 'customers:read'),
        ('manager', 'customers:update'),
        ('manager', 'expenses:create'),
        ('manager', 'expenses:read'),
        ('manager', 'expenses:update'),
        ('manager', 'reports:read'),
        ('manager', 'reports:export'),
        ('manager', 'ai:use'),
        ('manager', 'debts:read'),
        ('manager', 'debts:manage'),
        ('manager', 'debts:remind'),
        ('sales', 'sales:create'),
        ('sales', 'sales:read'),
        ('sales', 'customers:create'),
        ('sales', 'customers:read'),
        ('sales', 'inventory:read'),
        ('sales', 'debts:read'),
        ('sales', 'debts:remind'),
        ('viewer', 'sales:read'),
        ('viewer', 'purchases:read'),
        ('viewer', 'accounting:read'),
        ('viewer', 'inventory:read'),
        ('viewer', 'customers:read'),
        ('viewer', 'reports:read'),
        ('viewer', 'debts:read')
) AS v(role, permission)
WHERE NOT EXISTS (
  SELECT 1 FROM public.role_permissions rp
  WHERE rp.role = v.role AND rp.permission = v.permission
);
