-- ============================================================
-- SYNC: reproduce live state for the 2026-08-20 unpublished
-- migrations (applied to production via Management API but
-- never committed to the repo).
--   * fix_security_definer_views  -> security_invoker=true
--   * add_missing_fk_indexes     -> 155 indexes
-- Idempotent (IF NOT EXISTS / SET) - safe on both a fresh
-- build and the live DB. Date: 2026-08-21
-- ============================================================

-- Views: run as owner (security_invoker) instead of definer
-- (fixes the security_definer_view advisor findings: views
-- were evaluated with the OWNER permissions, bypassing RLS)

ALTER VIEW public.account_balances SET (security_invoker = true);
ALTER VIEW public.active_accounts SET (security_invoker = true);
ALTER VIEW public.active_expenses SET (security_invoker = true);
ALTER VIEW public.active_invoices SET (security_invoker = true);
ALTER VIEW public.active_journal_entries SET (security_invoker = true);
ALTER VIEW public.active_parties SET (security_invoker = true);
ALTER VIEW public.active_payments SET (security_invoker = true);
ALTER VIEW public.active_products SET (security_invoker = true);
ALTER VIEW public.low_stock_alert SET (security_invoker = true);
ALTER VIEW public.party_balances SET (security_invoker = true);
ALTER VIEW public.party_balances_by_currency SET (security_invoker = true);
ALTER VIEW public.user_profiles SET (security_invoker = true);
ALTER VIEW public.vw_income_statement SET (security_invoker = true);
ALTER VIEW public.vw_inventory_summary SET (security_invoker = true);
ALTER VIEW public.vw_inventory_valuation SET (security_invoker = true);
ALTER VIEW public.vw_sys_event_bus_health SET (security_invoker = true);
ALTER VIEW public.vw_sys_infrastructure_metrics SET (security_invoker = true);
ALTER VIEW public.vw_sys_queue_metrics SET (security_invoker = true);
ALTER VIEW public.vw_sys_workflow_metrics SET (security_invoker = true);
ALTER VIEW public.vw_trial_balance SET (security_invoker = true);

-- Missing FK / support indexes

CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_user_id ON public.ai_usage_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_sessions_completed_by ON public.audit_sessions USING btree (completed_by);
CREATE INDEX IF NOT EXISTS idx_backup_logs_company_id ON public.backup_logs USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_backup_logs_user_id ON public.backup_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_cashboxes_account_id ON public.cashboxes USING btree (account_id);
CREATE INDEX IF NOT EXISTS idx_cashboxes_branch_id ON public.cashboxes USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_cashboxes_company_id ON public.cashboxes USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_cashboxes_created_by ON public.cashboxes USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_cashboxes_currency_code ON public.cashboxes USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_companies_plan_id ON public.companies USING btree (plan_id);
CREATE INDEX IF NOT EXISTS idx_debt_message_log_created_by ON public.debt_message_log USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_debt_message_log_template_id ON public.debt_message_log USING btree (template_id);
CREATE INDEX IF NOT EXISTS idx_debt_payment_promises_created_by ON public.debt_payment_promises USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_exchange_companies_account_id ON public.exchange_companies USING btree (account_id);
CREATE INDEX IF NOT EXISTS idx_exchange_companies_branch_id ON public.exchange_companies USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_exchange_companies_company_id ON public.exchange_companies USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_exchange_companies_created_by ON public.exchange_companies USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_file_attachments_created_by ON public.file_attachments USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_adjustments_approved_by ON public.incentive_adjustments USING btree (approved_by);
CREATE INDEX IF NOT EXISTS idx_incentive_adjustments_calculation_id ON public.incentive_adjustments USING btree (calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_adjustments_company_id ON public.incentive_adjustments USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_incentive_adjustments_company_id_calculation_id ON public.incentive_adjustments USING btree (company_id, calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_adjustments_created_by ON public.incentive_adjustments USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_adjustments_original_calculation_id ON public.incentive_adjustments USING btree (original_calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_assignments_branch_id ON public.incentive_assignments USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_incentive_assignments_created_by ON public.incentive_assignments USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_assignments_plan_id ON public.incentive_assignments USING btree (plan_id);
CREATE INDEX IF NOT EXISTS idx_incentive_assignments_updated_by ON public.incentive_assignments USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_calculation_id ON public.incentive_calculation_lines USING btree (calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_company_id ON public.incentive_calculation_lines USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_company_id_calculation_id ON public.incentive_calculation_lines USING btree (company_id, calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_currency_code ON public.incentive_calculation_lines USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_invoice_id ON public.incentive_calculation_lines USING btree (invoice_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_invoice_line_id ON public.incentive_calculation_lines USING btree (invoice_line_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_rule_id ON public.incentive_calculation_lines USING btree (rule_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculation_lines_tier_id ON public.incentive_calculation_lines USING btree (tier_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculations_approved_by ON public.incentive_calculations USING btree (approved_by);
CREATE INDEX IF NOT EXISTS idx_incentive_calculations_calculated_by ON public.incentive_calculations USING btree (calculated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_calculations_currency_code ON public.incentive_calculations USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_calculations_period_id ON public.incentive_calculations USING btree (period_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculations_plan_id ON public.incentive_calculations USING btree (plan_id);
CREATE INDEX IF NOT EXISTS idx_incentive_calculations_user_id ON public.incentive_calculations USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_incentive_engineer_links_assigned_by ON public.incentive_engineer_links USING btree (assigned_by);
CREATE INDEX IF NOT EXISTS idx_incentive_engineer_links_company_id_invoice_id ON public.incentive_engineer_links USING btree (company_id, invoice_id);
CREATE INDEX IF NOT EXISTS idx_incentive_payments_account_id ON public.incentive_payments USING btree (account_id);
CREATE INDEX IF NOT EXISTS idx_incentive_payments_company_id_calculation_id ON public.incentive_payments USING btree (company_id, calculation_id);
CREATE INDEX IF NOT EXISTS idx_incentive_payments_created_by ON public.incentive_payments USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_payments_currency_code ON public.incentive_payments USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_payments_user_id ON public.incentive_payments USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_incentive_pending_invoices_created_by ON public.incentive_pending_invoices USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_pending_invoices_invoice_id ON public.incentive_pending_invoices USING btree (invoice_id);
CREATE INDEX IF NOT EXISTS idx_incentive_pending_invoices_resolved_by ON public.incentive_pending_invoices USING btree (resolved_by);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_approved_by ON public.incentive_periods USING btree (approved_by);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_branch_id ON public.incentive_periods USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_created_by ON public.incentive_periods USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_currency_code ON public.incentive_periods USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_fiscal_year_id ON public.incentive_periods USING btree (fiscal_year_id);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_locked_by ON public.incentive_periods USING btree (locked_by);
CREATE INDEX IF NOT EXISTS idx_incentive_periods_paid_by ON public.incentive_periods USING btree (paid_by);
CREATE INDEX IF NOT EXISTS idx_incentive_plans_created_by ON public.incentive_plans USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_plans_currency_code ON public.incentive_plans USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_plans_tier_currency_code ON public.incentive_plans USING btree (tier_currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_plans_updated_by ON public.incentive_plans USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_rules_created_by ON public.incentive_rules USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_rules_tier_currency_code ON public.incentive_rules USING btree (tier_currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_rules_updated_by ON public.incentive_rules USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_targets_branch_id ON public.incentive_targets USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_incentive_targets_company_id ON public.incentive_targets USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_incentive_targets_created_by ON public.incentive_targets USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_incentive_targets_currency_code ON public.incentive_targets USING btree (currency_code);
CREATE INDEX IF NOT EXISTS idx_incentive_targets_updated_by ON public.incentive_targets USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_incentive_targets_user_id ON public.incentive_targets USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_incentive_tiers_company_id ON public.incentive_tiers USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_incentive_tiers_tier_currency_code ON public.incentive_tiers USING btree (tier_currency_code);
CREATE INDEX IF NOT EXISTS idx_inv_stock_audit_items_audit_id ON public.inv_stock_audit_items USING btree (audit_id);
CREATE INDEX IF NOT EXISTS idx_inv_stock_movement_items_movement_id ON public.inv_stock_movement_items USING btree (movement_id);
CREATE INDEX IF NOT EXISTS idx_inv_stock_movements_to_warehouse_id ON public.inv_stock_movements USING btree (to_warehouse_id);
CREATE INDEX IF NOT EXISTS idx_inventory_session_drafts_warehouse_id ON public.inventory_session_drafts USING btree (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_invitations_branch_id ON public.invitations USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_invoices_payment_account_id ON public.invoices USING btree (payment_account_id);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_branch_id ON public.journal_entry_lines USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_monthly_targets_branch_id ON public.monthly_targets USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_party_opening_balances_created_by ON public.party_opening_balances USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_payments_counterparty_account_id ON public.payments USING btree (counterparty_account_id);
CREATE INDEX IF NOT EXISTS idx_prc_contract_items_contract_id ON public.prc_contract_items USING btree (contract_id);
CREATE INDEX IF NOT EXISTS idx_prc_goods_receipt_documents_grn_id ON public.prc_goods_receipt_documents USING btree (grn_id);
CREATE INDEX IF NOT EXISTS idx_prc_goods_receipt_items_grn_id ON public.prc_goods_receipt_items USING btree (grn_id);
CREATE INDEX IF NOT EXISTS idx_prc_goods_receipt_items_po_item_id ON public.prc_goods_receipt_items USING btree (po_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_goods_receipts_po_id ON public.prc_goods_receipts USING btree (po_id);
CREATE INDEX IF NOT EXISTS idx_prc_goods_receipts_supplier_id ON public.prc_goods_receipts USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_invoice_items_grn_item_id ON public.prc_purchase_invoice_items USING btree (grn_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_invoice_items_invoice_id ON public.prc_purchase_invoice_items USING btree (invoice_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_invoice_items_po_item_id ON public.prc_purchase_invoice_items USING btree (po_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_invoices_po_id ON public.prc_purchase_invoices USING btree (po_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_invoices_supplier_id ON public.prc_purchase_invoices USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_order_documents_po_id ON public.prc_purchase_order_documents USING btree (po_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_order_items_po_id ON public.prc_purchase_order_items USING btree (po_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_order_items_pr_item_id ON public.prc_purchase_order_items USING btree (pr_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_orders_contract_id ON public.prc_purchase_orders USING btree (contract_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_orders_quotation_id ON public.prc_purchase_orders USING btree (quotation_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_orders_rfq_id ON public.prc_purchase_orders USING btree (rfq_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_orders_supplier_id ON public.prc_purchase_orders USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_request_documents_pr_id ON public.prc_purchase_request_documents USING btree (pr_id);
CREATE INDEX IF NOT EXISTS idx_prc_purchase_request_items_pr_id ON public.prc_purchase_request_items USING btree (pr_id);
CREATE INDEX IF NOT EXISTS idx_prc_quotation_documents_quotation_id ON public.prc_quotation_documents USING btree (quotation_id);
CREATE INDEX IF NOT EXISTS idx_prc_quotation_items_quotation_id ON public.prc_quotation_items USING btree (quotation_id);
CREATE INDEX IF NOT EXISTS idx_prc_quotation_items_rfq_item_id ON public.prc_quotation_items USING btree (rfq_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_quotations_supplier_id ON public.prc_quotations USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_evaluation_items_awarded_quotation_item_id ON public.prc_rfq_evaluation_items USING btree (awarded_quotation_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_evaluation_items_evaluation_id ON public.prc_rfq_evaluation_items USING btree (evaluation_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_evaluation_items_rfq_item_id ON public.prc_rfq_evaluation_items USING btree (rfq_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_evaluation_scores_quotation_id ON public.prc_rfq_evaluation_scores USING btree (quotation_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_evaluations_rfq_id ON public.prc_rfq_evaluations USING btree (rfq_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_evaluations_selected_quotation_id ON public.prc_rfq_evaluations USING btree (selected_quotation_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_items_pr_item_id ON public.prc_rfq_items USING btree (pr_item_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_items_rfq_id ON public.prc_rfq_items USING btree (rfq_id);
CREATE INDEX IF NOT EXISTS idx_prc_rfq_suppliers_supplier_id ON public.prc_rfq_suppliers USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_addresses_supplier_id ON public.prc_supplier_addresses USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_bank_accounts_supplier_id ON public.prc_supplier_bank_accounts USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_categories_parent_category_id ON public.prc_supplier_categories USING btree (parent_category_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_contacts_supplier_id ON public.prc_supplier_contacts USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_contracts_supplier_id ON public.prc_supplier_contracts USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_documents_supplier_id ON public.prc_supplier_documents USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_metrics_supplier_id ON public.prc_supplier_metrics USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_prices_supplier_product_id ON public.prc_supplier_prices USING btree (supplier_product_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_sla_violations_sla_id ON public.prc_supplier_sla_violations USING btree (sla_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_sla_violations_supplier_id ON public.prc_supplier_sla_violations USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_supplier_slas_supplier_id ON public.prc_supplier_slas USING btree (supplier_id);
CREATE INDEX IF NOT EXISTS idx_prc_suppliers_category_id ON public.prc_suppliers USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_prc_three_way_matches_invoice_id ON public.prc_three_way_matches USING btree (invoice_id);
CREATE INDEX IF NOT EXISTS idx_prc_three_way_matches_po_id ON public.prc_three_way_matches USING btree (po_id);
CREATE INDEX IF NOT EXISTS idx_product_uoms_product_id ON public.product_uoms USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_suspended_orders_branch_id ON public.suspended_orders USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_suspended_orders_company_id ON public.suspended_orders USING btree (company_id);
CREATE INDEX IF NOT EXISTS idx_suspended_orders_user_id ON public.suspended_orders USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_sys_job_queue_job_type ON public.sys_job_queue USING btree (job_type);
CREATE INDEX IF NOT EXISTS idx_sys_job_queue_worker_id ON public.sys_job_queue USING btree (worker_id);
CREATE INDEX IF NOT EXISTS idx_sys_notification_queue_template_id ON public.sys_notification_queue USING btree (template_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_conditions_transition_id ON public.sys_workflow_conditions USING btree (transition_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_definitions_calendar_id ON public.sys_workflow_definitions USING btree (calendar_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_definitions_template_id ON public.sys_workflow_definitions USING btree (template_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_history_from_state_id ON public.sys_workflow_history USING btree (from_state_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_history_instance_id ON public.sys_workflow_history USING btree (instance_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_history_to_state_id ON public.sys_workflow_history USING btree (to_state_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_history_transition_id ON public.sys_workflow_history USING btree (transition_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_instances_current_state_id ON public.sys_workflow_instances USING btree (current_state_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_instances_parent_instance_id ON public.sys_workflow_instances USING btree (parent_instance_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_instances_workflow_id ON public.sys_workflow_instances USING btree (workflow_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_states_sub_workflow_id ON public.sys_workflow_states USING btree (sub_workflow_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_states_workflow_id ON public.sys_workflow_states USING btree (workflow_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_transitions_from_state_id ON public.sys_workflow_transitions USING btree (from_state_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_transitions_to_state_id ON public.sys_workflow_transitions USING btree (to_state_id);
CREATE INDEX IF NOT EXISTS idx_sys_workflow_transitions_workflow_id ON public.sys_workflow_transitions USING btree (workflow_id);
CREATE INDEX IF NOT EXISTS idx_system_broadcasts_created_by ON public.system_broadcasts USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_vin_analyses_vehicle_id ON public.vin_analyses USING btree (vehicle_id);
