# ============================================================
# PRIVILEGES: function EXECUTE hardening (baseline companion)
# Date: 2026-08-18
#
# The schema/functions/triggers baselines are generated schema-only and do
# NOT capture grants. Supabase grants default PUBLIC EXECUTE on new
# functions, which lets the anon role invoke every one of them. This file
# re-applies the hardening applied to the live project:
#   - revoke EXECUTE from PUBLIC and anon
#   - grant EXECUTE to authenticated only (frontend role)
# service_role keeps its explicit grants. The 12 functions used by RLS
# policies / views are intentionally left anon-executable.
# ============================================================

GRANT EXECUTE ON FUNCTION admin_recalculate_all_stock(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_fin_generate_grn_je(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_fin_post_journal_entry(uuid,date,character varying,uuid,text,jsonb,uuid,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_inv_create_warehouse(uuid,character varying,character varying,character varying,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_inv_record_movement(uuid,uuid,inv_movement_type,character varying,uuid,jsonb,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_accept_grn(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_act_on_pr(uuid,uuid,character varying,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_add_supplier_product(uuid,uuid,uuid,character varying,numeric,numeric,smallint,boolean,smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_approve_supplier(uuid,uuid,boolean,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_approve_variance(uuid,uuid,uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_award_rfq(uuid,uuid,uuid,text,uuid,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_block_supplier(uuid,uuid,character varying,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_calculate_ranking(uuid,uuid,numeric,numeric,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_calculate_supplier_metrics(uuid,uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_cancel_po(uuid,uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_cancel_pr(uuid,uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_close_rfq(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_create_grn(uuid,uuid,uuid,character varying,uuid,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_create_po_from_quotation(uuid,uuid,uuid,date,character varying,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_create_pr(uuid,uuid,uuid,text,character varying,date,character varying,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_create_rfq(uuid,uuid,character varying,timestamp with time zone,date,text,jsonb,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_create_supplier(uuid,character varying,character varying,character varying,uuid,character varying,character varying,character varying,character varying,character varying,character varying,character varying,smallint) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_instantiate_pr_workflow(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_invite_supplier_to_rfq(uuid,uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_issue_po(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_publish_rfq(uuid,uuid,uuid,uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_record_supplier_document(uuid,uuid,character varying,character varying,character varying,date,date,smallint[],uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_run_three_way_match(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_schedule_analytics_job(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_score_quotation(uuid,uuid,uuid,numeric,numeric,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_start_evaluation(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_submit_pr(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_submit_quotation(uuid,uuid,uuid,character varying,date,character varying,smallint,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_submit_supplier_approval(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_update_supplier_scores(uuid,uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_update_supplier_terms(uuid,uuid,character varying,numeric,smallint,character varying,character varying,character varying,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_prc_upsert_supplier_price(uuid,uuid,numeric,character varying,numeric,numeric,numeric,timestamp with time zone,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_sys_enqueue_job(uuid,character varying,jsonb,uuid,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_sys_is_feature_enabled(character varying,uuid,uuid,character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION api_v1_sys_worker_heartbeat(character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION assemble_kit(uuid,uuid,uuid,integer,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION assert_account_belongs_to_company(uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION assert_party_belongs_to_company(uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION assert_product_belongs_to_company(uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION audit_table_changes() TO authenticated;
GRANT EXECUTE ON FUNCTION auto_assign_fiscal_year_to_invoice() TO authenticated;
GRANT EXECUTE ON FUNCTION auto_journal_from_invoice(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION break_overdue_promises(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION bulk_adjust_stock(uuid,uuid,jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION bulk_update_product_prices(uuid,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION calculate_product_cogs(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION check_rate_limit(uuid,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION check_stock_availability(uuid,uuid,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION cleanup_old_audit_logs() TO authenticated;
GRANT EXECUTE ON FUNCTION cleanup_old_records() TO authenticated;
GRANT EXECUTE ON FUNCTION complete_promise(uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION convert_quotation_to_invoice(uuid,date,date,text) TO authenticated;
GRANT EXECUTE ON FUNCTION create_cashbox(uuid,uuid,text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION create_exchange_company(uuid,uuid,text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION create_stock_transfer(uuid,uuid,jsonb,uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION disassemble_kit(uuid,uuid,uuid,integer,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION finalize_audit_session(uuid,uuid,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION fn_accounting_health_check() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_assert_company_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION fn_auto_post_invoice_journal() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_auto_post_payment_journal() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_inventory_transaction_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_invoice_item_product_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_invoice_party_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_journal_line_account_postable() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_journal_line_account_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_journal_line_entry_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_journal_line_party_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_payment_account_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_check_payment_party_tenant() TO authenticated;
GRANT EXECUTE ON FUNCTION fn_post_inventory_movement(uuid,uuid,uuid,numeric,text,text,uuid,uuid,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION fn_release_payment_allocations(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION fn_reverse_inventory_for_reference(uuid,text[],text) TO authenticated;
GRANT EXECUTE ON FUNCTION fn_reverse_journal_entries(uuid,text[],text,text,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION fn_validate_invoice_business_rules() TO authenticated;
GRANT EXECUTE ON FUNCTION get_account_ledger(uuid,uuid,text,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_all_parties(uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_auth_company_id() TO authenticated;
GRANT EXECUTE ON FUNCTION get_bonds_stats(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_cash_account(text,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_cash_liquidity(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_changes_since(uuid,timestamp with time zone,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION get_company_settings(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_customer_stats(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_dashboard_summary(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_dashboard_summary(uuid,uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION get_dashboard_totals(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_dead_stock(uuid,integer,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_debt_analytics_summary(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_debt_followup_dashboard(uuid,integer,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_debt_party_overview(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_debt_today_tasks(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_expense_categories_summary(uuid,date,date,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_expense_stats(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_inventory_valuation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_invoice_with_items(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_item_movements_with_balance(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_low_stock_products(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_monthly_performance(uuid,integer,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_next_invoice_number(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_next_sequence(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_overdue_invoices(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_paginated_invoices(uuid,text,text,uuid,date,date,text,integer,integer,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_party_all_balances(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_party_balance_by_currency(uuid,uuid,character varying) TO authenticated;
GRANT EXECUTE ON FUNCTION get_party_statement(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_party_summary(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_popular_products(uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_potential_duplicates(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION get_product_analytics(uuid,uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_product_fitment(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_product_stock_history(uuid,uuid,uuid,date,date,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_purchase_stats(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_sales_analytics(uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION get_sales_chart_data(uuid,uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION get_sales_stats(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_similar_products(text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_stock_valuation(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_top_customers_by_revenue(uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_top_products_and_customers(uuid,uuid,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_top_selling_products(uuid,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION get_user_permissions() TO authenticated;
GRANT EXECUTE ON FUNCTION get_user_profile(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_vehicle_products(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION get_warehouses_with_stats(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION handle_new_user() TO authenticated;
GRANT EXECUTE ON FUNCTION log_audit_event() TO authenticated;
GRANT EXECUTE ON FUNCTION log_cron_backup_event() TO authenticated;
GRANT EXECUTE ON FUNCTION log_table_changes() TO authenticated;
GRANT EXECUTE ON FUNCTION normalize_arabic(text) TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_invoice_in_closed_fiscal_year() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_journal_entry_in_closed_fiscal_year() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_posted_journal_edit() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_posted_journal_line_modification() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_posted_journal_modification() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_sys_activity_log_modification() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_sys_domain_events_deletion() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_sys_domain_events_payload_update() TO authenticated;
GRANT EXECUTE ON FUNCTION prevent_system_account_modification() TO authenticated;
GRANT EXECUTE ON FUNCTION public.commit_expense_v2(uuid, uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commit_payment(uuid, uuid, text, numeric, date, uuid, text, uuid, text, text, text, text, numeric, numeric, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commit_purchase_invoice(uuid, uuid, uuid, jsonb, numeric, text, date, text, uuid, text, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commit_purchase_return(uuid, uuid, uuid, jsonb, text, text, numeric, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commit_sale_return(uuid, uuid, uuid, jsonb, numeric, text, uuid, text, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commit_sales_invoice_v2(uuid, date, date, jsonb, text, text, text, numeric, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_financial_bond(uuid, text, numeric, text, numeric, numeric, date, uuid, uuid, text, text, uuid, uuid, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.post_manual_journal(uuid, uuid, date, text, jsonb, text, numeric, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_sales_return(uuid, uuid, text, jsonb, text, text, text, date, text, numeric, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_stock_transfer(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_all_party_balances() TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_party_balance(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recalculate_product_stock(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_bond(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.void_expense(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION recalculate_party_balance_from_ledger(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION recalculate_product_stock_for_warehouse(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION record_debt_reminder(uuid,uuid,text,character varying,uuid,character varying,character varying,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION report_balance_sheet(uuid,date) TO authenticated;
GRANT EXECUTE ON FUNCTION report_cash_flow(uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION report_debt_aging(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION report_debts(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION report_profit_loss(uuid,date,date) TO authenticated;
GRANT EXECUTE ON FUNCTION report_trial_balance(uuid,date,date,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION reverse_audit_session(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION reverse_stock_transfer(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION save_product_uoms(uuid,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION search_by_oem(uuid,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION search_cached_parts(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION search_cached_xrefs(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION search_inventory(text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION search_inventory_paginated(uuid,text,integer,integer,text,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION search_parties(uuid,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION send_webhook_event() TO authenticated;
GRANT EXECUTE ON FUNCTION setup_new_company() TO authenticated;
GRANT EXECUTE ON FUNCTION sync_party_stats_on_invoice_change() TO authenticated;
GRANT EXECUTE ON FUNCTION sync_product_search_numbers(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION test_active_accounts(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION trg_incentive_calc_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION trg_incentive_lines_period_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION trg_incentive_links_period_guard() TO authenticated;
GRANT EXECUTE ON FUNCTION trg_invoice_soft_delete_propagation() TO authenticated;
GRANT EXECUTE ON FUNCTION trg_sync_inventory_stock_on_delete() TO authenticated;
GRANT EXECUTE ON FUNCTION trg_sync_product_search_numbers() TO authenticated;
GRANT EXECUTE ON FUNCTION trg_update_product_stock() TO authenticated;
GRANT EXECUTE ON FUNCTION user_has_company_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION validate_data_integrity(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION validate_journal_entry_balance(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION validate_payment_allocation_company() TO authenticated;
GRANT EXECUTE ON FUNCTION verify_company_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION void_invoice(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION admin_recalculate_all_stock(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION admin_recalculate_all_stock(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_fin_generate_grn_je(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_fin_generate_grn_je(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_fin_post_journal_entry(uuid,date,character varying,uuid,text,jsonb,uuid,boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_fin_post_journal_entry(uuid,date,character varying,uuid,text,jsonb,uuid,boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_inv_create_warehouse(uuid,character varying,character varying,character varying,text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_inv_create_warehouse(uuid,character varying,character varying,character varying,text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_inv_record_movement(uuid,uuid,inv_movement_type,character varying,uuid,jsonb,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_inv_record_movement(uuid,uuid,inv_movement_type,character varying,uuid,jsonb,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_accept_grn(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_accept_grn(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_act_on_pr(uuid,uuid,character varying,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_act_on_pr(uuid,uuid,character varying,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_add_supplier_product(uuid,uuid,uuid,character varying,numeric,numeric,smallint,boolean,smallint) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_add_supplier_product(uuid,uuid,uuid,character varying,numeric,numeric,smallint,boolean,smallint) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_approve_supplier(uuid,uuid,boolean,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_approve_supplier(uuid,uuid,boolean,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_approve_variance(uuid,uuid,uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_approve_variance(uuid,uuid,uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_award_rfq(uuid,uuid,uuid,text,uuid,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_award_rfq(uuid,uuid,uuid,text,uuid,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_block_supplier(uuid,uuid,character varying,text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_block_supplier(uuid,uuid,character varying,text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_calculate_ranking(uuid,uuid,numeric,numeric,numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_calculate_ranking(uuid,uuid,numeric,numeric,numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_calculate_supplier_metrics(uuid,uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_calculate_supplier_metrics(uuid,uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_cancel_po(uuid,uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_cancel_po(uuid,uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_cancel_pr(uuid,uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_cancel_pr(uuid,uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_close_rfq(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_close_rfq(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_grn(uuid,uuid,uuid,character varying,uuid,text,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_grn(uuid,uuid,uuid,character varying,uuid,text,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_po_from_quotation(uuid,uuid,uuid,date,character varying,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_po_from_quotation(uuid,uuid,uuid,date,character varying,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_pr(uuid,uuid,uuid,text,character varying,date,character varying,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_pr(uuid,uuid,uuid,text,character varying,date,character varying,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_rfq(uuid,uuid,character varying,timestamp with time zone,date,text,jsonb,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_rfq(uuid,uuid,character varying,timestamp with time zone,date,text,jsonb,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_supplier(uuid,character varying,character varying,character varying,uuid,character varying,character varying,character varying,character varying,character varying,character varying,character varying,smallint) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_create_supplier(uuid,character varying,character varying,character varying,uuid,character varying,character varying,character varying,character varying,character varying,character varying,character varying,smallint) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_instantiate_pr_workflow(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_instantiate_pr_workflow(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_invite_supplier_to_rfq(uuid,uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_invite_supplier_to_rfq(uuid,uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_issue_po(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_issue_po(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_publish_rfq(uuid,uuid,uuid,uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_publish_rfq(uuid,uuid,uuid,uuid[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_record_supplier_document(uuid,uuid,character varying,character varying,character varying,date,date,smallint[],uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_record_supplier_document(uuid,uuid,character varying,character varying,character varying,date,date,smallint[],uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_run_three_way_match(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_run_three_way_match(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_schedule_analytics_job(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_schedule_analytics_job(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_score_quotation(uuid,uuid,uuid,numeric,numeric,numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_score_quotation(uuid,uuid,uuid,numeric,numeric,numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_start_evaluation(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_start_evaluation(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_submit_pr(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_submit_pr(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_submit_quotation(uuid,uuid,uuid,character varying,date,character varying,smallint,text,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_submit_quotation(uuid,uuid,uuid,character varying,date,character varying,smallint,text,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_submit_supplier_approval(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_submit_supplier_approval(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_update_supplier_scores(uuid,uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_update_supplier_scores(uuid,uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_update_supplier_terms(uuid,uuid,character varying,numeric,smallint,character varying,character varying,character varying,text,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_update_supplier_terms(uuid,uuid,character varying,numeric,smallint,character varying,character varying,character varying,text,text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_prc_upsert_supplier_price(uuid,uuid,numeric,character varying,numeric,numeric,numeric,timestamp with time zone,timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_prc_upsert_supplier_price(uuid,uuid,numeric,character varying,numeric,numeric,numeric,timestamp with time zone,timestamp with time zone) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_sys_enqueue_job(uuid,character varying,jsonb,uuid,timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_sys_enqueue_job(uuid,character varying,jsonb,uuid,timestamp with time zone) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_sys_is_feature_enabled(character varying,uuid,uuid,character varying) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_sys_is_feature_enabled(character varying,uuid,uuid,character varying) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION api_v1_sys_worker_heartbeat(character varying) FROM anon;
REVOKE EXECUTE ON FUNCTION api_v1_sys_worker_heartbeat(character varying) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION assemble_kit(uuid,uuid,uuid,integer,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION assemble_kit(uuid,uuid,uuid,integer,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION assert_account_belongs_to_company(uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION assert_account_belongs_to_company(uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION assert_party_belongs_to_company(uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION assert_party_belongs_to_company(uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION assert_product_belongs_to_company(uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION assert_product_belongs_to_company(uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION audit_table_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION audit_table_changes() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION auto_assign_fiscal_year_to_invoice() FROM anon;
REVOKE EXECUTE ON FUNCTION auto_assign_fiscal_year_to_invoice() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION auto_journal_from_invoice(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION auto_journal_from_invoice(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION break_overdue_promises(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION break_overdue_promises(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION bulk_adjust_stock(uuid,uuid,jsonb,text) FROM anon;
REVOKE EXECUTE ON FUNCTION bulk_adjust_stock(uuid,uuid,jsonb,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION bulk_update_product_prices(uuid,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION bulk_update_product_prices(uuid,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION calculate_product_cogs(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION calculate_product_cogs(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION check_rate_limit(uuid,text,integer,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION check_rate_limit(uuid,text,integer,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION check_stock_availability(uuid,uuid,numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION check_stock_availability(uuid,uuid,numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION cleanup_old_audit_logs() FROM anon;
REVOKE EXECUTE ON FUNCTION cleanup_old_audit_logs() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION cleanup_old_records() FROM anon;
REVOKE EXECUTE ON FUNCTION cleanup_old_records() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION complete_promise(uuid,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION complete_promise(uuid,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION convert_quotation_to_invoice(uuid,date,date,text) FROM anon;
REVOKE EXECUTE ON FUNCTION convert_quotation_to_invoice(uuid,date,date,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_cashbox(uuid,uuid,text,text,numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION create_cashbox(uuid,uuid,text,text,numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_exchange_company(uuid,uuid,text,text,numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION create_exchange_company(uuid,uuid,text,text,numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_stock_transfer(uuid,uuid,jsonb,uuid,uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION create_stock_transfer(uuid,uuid,jsonb,uuid,uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION disassemble_kit(uuid,uuid,uuid,integer,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION disassemble_kit(uuid,uuid,uuid,integer,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION finalize_audit_session(uuid,uuid,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION finalize_audit_session(uuid,uuid,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_accounting_health_check() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_accounting_health_check() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_assert_company_access(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION fn_assert_company_access(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_auto_post_invoice_journal() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_auto_post_invoice_journal() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_auto_post_payment_journal() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_auto_post_payment_journal() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_inventory_transaction_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_inventory_transaction_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_invoice_item_product_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_invoice_item_product_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_invoice_party_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_invoice_party_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_account_postable() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_account_postable() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_account_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_account_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_entry_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_entry_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_party_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_journal_line_party_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_payment_account_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_payment_account_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_check_payment_party_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_check_payment_party_tenant() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_post_inventory_movement(uuid,uuid,uuid,numeric,text,text,uuid,uuid,numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION fn_post_inventory_movement(uuid,uuid,uuid,numeric,text,text,uuid,uuid,numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_release_payment_allocations(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION fn_release_payment_allocations(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_reverse_inventory_for_reference(uuid,text[],text) FROM anon;
REVOKE EXECUTE ON FUNCTION fn_reverse_inventory_for_reference(uuid,text[],text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_reverse_journal_entries(uuid,text[],text,text,uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION fn_reverse_journal_entries(uuid,text[],text,text,uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION fn_validate_invoice_business_rules() FROM anon;
REVOKE EXECUTE ON FUNCTION fn_validate_invoice_business_rules() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_account_ledger(uuid,uuid,text,text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_account_ledger(uuid,uuid,text,text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_all_parties(uuid,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_all_parties(uuid,text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_auth_company_id() FROM anon;
REVOKE EXECUTE ON FUNCTION get_auth_company_id() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_bonds_stats(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_bonds_stats(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_cash_account(text,text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_cash_account(text,text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_cash_liquidity(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_cash_liquidity(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_changes_since(uuid,timestamp with time zone,text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION get_changes_since(uuid,timestamp with time zone,text[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_company_settings(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_company_settings(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_customer_stats(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_customer_stats(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_dashboard_summary(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_dashboard_summary(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_dashboard_summary(uuid,uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION get_dashboard_summary(uuid,uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_dashboard_totals(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_dashboard_totals(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_dead_stock(uuid,integer,integer,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_dead_stock(uuid,integer,integer,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_debt_analytics_summary(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_debt_analytics_summary(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_debt_followup_dashboard(uuid,integer,integer,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_debt_followup_dashboard(uuid,integer,integer,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_debt_party_overview(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_debt_party_overview(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_debt_today_tasks(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_debt_today_tasks(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_expense_categories_summary(uuid,date,date,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_expense_categories_summary(uuid,date,date,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_expense_stats(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_expense_stats(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_inventory_valuation(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_inventory_valuation(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_invoice_with_items(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_invoice_with_items(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_item_movements_with_balance(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_item_movements_with_balance(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_low_stock_products(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_low_stock_products(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_monthly_performance(uuid,integer,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_monthly_performance(uuid,integer,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_next_invoice_number(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_next_invoice_number(uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_next_sequence(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_next_sequence(uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_overdue_invoices(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_overdue_invoices(uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_paginated_invoices(uuid,text,text,uuid,date,date,text,integer,integer,text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_paginated_invoices(uuid,text,text,uuid,date,date,text,integer,integer,text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_party_all_balances(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_party_all_balances(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_party_balance_by_currency(uuid,uuid,character varying) FROM anon;
REVOKE EXECUTE ON FUNCTION get_party_balance_by_currency(uuid,uuid,character varying) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_party_statement(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_party_statement(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_party_summary(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_party_summary(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_popular_products(uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_popular_products(uuid,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_potential_duplicates(uuid,text) FROM anon;
REVOKE EXECUTE ON FUNCTION get_potential_duplicates(uuid,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_product_analytics(uuid,uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_product_analytics(uuid,uuid,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_product_fitment(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_product_fitment(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_product_stock_history(uuid,uuid,uuid,date,date,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_product_stock_history(uuid,uuid,uuid,date,date,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_purchase_stats(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_purchase_stats(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_sales_analytics(uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION get_sales_analytics(uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_sales_chart_data(uuid,uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION get_sales_chart_data(uuid,uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_sales_stats(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_sales_stats(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_similar_products(text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_similar_products(text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_stock_valuation(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_stock_valuation(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_top_customers_by_revenue(uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_top_customers_by_revenue(uuid,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_top_products_and_customers(uuid,uuid,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_top_products_and_customers(uuid,uuid,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_top_selling_products(uuid,integer,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION get_top_selling_products(uuid,integer,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_user_permissions() FROM anon;
REVOKE EXECUTE ON FUNCTION get_user_permissions() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_user_profile(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_user_profile(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_vehicle_products(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_vehicle_products(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION get_warehouses_with_stats(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION get_warehouses_with_stats(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION handle_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION log_audit_event() FROM anon;
REVOKE EXECUTE ON FUNCTION log_audit_event() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION log_cron_backup_event() FROM anon;
REVOKE EXECUTE ON FUNCTION log_cron_backup_event() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION log_table_changes() FROM anon;
REVOKE EXECUTE ON FUNCTION log_table_changes() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION normalize_arabic(text) FROM anon;
REVOKE EXECUTE ON FUNCTION normalize_arabic(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_invoice_in_closed_fiscal_year() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_invoice_in_closed_fiscal_year() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_journal_entry_in_closed_fiscal_year() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_journal_entry_in_closed_fiscal_year() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_posted_journal_edit() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_posted_journal_edit() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_posted_journal_line_modification() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_posted_journal_line_modification() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_posted_journal_modification() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_posted_journal_modification() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_sys_activity_log_modification() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_sys_activity_log_modification() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_sys_domain_events_deletion() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_sys_domain_events_deletion() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_sys_domain_events_payload_update() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_sys_domain_events_payload_update() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION prevent_system_account_modification() FROM anon;
REVOKE EXECUTE ON FUNCTION prevent_system_account_modification() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.commit_expense_v2(uuid, uuid, jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.commit_expense_v2(uuid, uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.commit_payment(uuid, uuid, text, numeric, date, uuid, text, uuid, text, text, text, text, numeric, numeric, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.commit_payment(uuid, uuid, text, numeric, date, uuid, text, uuid, text, text, text, text, numeric, numeric, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.commit_purchase_invoice(uuid, uuid, uuid, jsonb, numeric, text, date, text, uuid, text, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.commit_purchase_invoice(uuid, uuid, uuid, jsonb, numeric, text, date, text, uuid, text, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.commit_purchase_return(uuid, uuid, uuid, jsonb, text, text, numeric, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.commit_purchase_return(uuid, uuid, uuid, jsonb, text, text, numeric, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.commit_sale_return(uuid, uuid, uuid, jsonb, numeric, text, uuid, text, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.commit_sale_return(uuid, uuid, uuid, jsonb, numeric, text, uuid, text, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.commit_sales_invoice_v2(uuid, date, date, jsonb, text, text, text, numeric, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.commit_sales_invoice_v2(uuid, date, date, jsonb, text, text, text, numeric, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_financial_bond(uuid, text, numeric, text, numeric, numeric, date, uuid, uuid, text, text, uuid, uuid, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_financial_bond(uuid, text, numeric, text, numeric, numeric, date, uuid, uuid, text, text, uuid, uuid, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.post_manual_journal(uuid, uuid, date, text, jsonb, text, numeric, text, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.post_manual_journal(uuid, uuid, date, text, jsonb, text, numeric, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.process_sales_return(uuid, uuid, text, jsonb, text, text, text, date, text, numeric, uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_sales_return(uuid, uuid, text, jsonb, text, text, text, date, text, numeric, uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.process_stock_transfer(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_stock_transfer(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_all_party_balances() FROM anon;
REVOKE EXECUTE ON FUNCTION public.recalculate_all_party_balances() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_party_balance(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.recalculate_party_balance(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_product_stock(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.recalculate_product_stock(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_bond(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.void_bond(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_expense(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.void_expense(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION recalculate_party_balance_from_ledger(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION recalculate_party_balance_from_ledger(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION recalculate_product_stock_for_warehouse(uuid,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION recalculate_product_stock_for_warehouse(uuid,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION record_debt_reminder(uuid,uuid,text,character varying,uuid,character varying,character varying,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION record_debt_reminder(uuid,uuid,text,character varying,uuid,character varying,character varying,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION report_balance_sheet(uuid,date) FROM anon;
REVOKE EXECUTE ON FUNCTION report_balance_sheet(uuid,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION report_cash_flow(uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION report_cash_flow(uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION report_debt_aging(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION report_debt_aging(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION report_debts(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION report_debts(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION report_profit_loss(uuid,date,date) FROM anon;
REVOKE EXECUTE ON FUNCTION report_profit_loss(uuid,date,date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION report_trial_balance(uuid,date,date,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION report_trial_balance(uuid,date,date,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION reverse_audit_session(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION reverse_audit_session(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION reverse_stock_transfer(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION reverse_stock_transfer(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION save_product_uoms(uuid,jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION save_product_uoms(uuid,jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_by_oem(uuid,text,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION search_by_oem(uuid,text,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_cached_parts(text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION search_cached_parts(text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_cached_xrefs(text,text) FROM anon;
REVOKE EXECUTE ON FUNCTION search_cached_xrefs(text,text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_inventory(text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION search_inventory(text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_inventory_paginated(uuid,text,integer,integer,text,text,uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION search_inventory_paginated(uuid,text,integer,integer,text,text,uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION search_parties(uuid,text,text,integer) FROM anon;
REVOKE EXECUTE ON FUNCTION search_parties(uuid,text,text,integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION send_webhook_event() FROM anon;
REVOKE EXECUTE ON FUNCTION send_webhook_event() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION setup_new_company() FROM anon;
REVOKE EXECUTE ON FUNCTION setup_new_company() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION sync_party_stats_on_invoice_change() FROM anon;
REVOKE EXECUTE ON FUNCTION sync_party_stats_on_invoice_change() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION sync_product_search_numbers(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION sync_product_search_numbers(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION test_active_accounts(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION test_active_accounts(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_incentive_calc_guard() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_incentive_calc_guard() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_incentive_lines_period_guard() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_incentive_lines_period_guard() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_incentive_links_period_guard() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_incentive_links_period_guard() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_invoice_soft_delete_propagation() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_invoice_soft_delete_propagation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_sync_inventory_stock_on_delete() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_sync_inventory_stock_on_delete() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_sync_product_search_numbers() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_sync_product_search_numbers() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION trg_update_product_stock() FROM anon;
REVOKE EXECUTE ON FUNCTION trg_update_product_stock() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION user_has_company_access(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION user_has_company_access(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION validate_data_integrity(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION validate_data_integrity(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION validate_journal_entry_balance(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION validate_journal_entry_balance(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION validate_payment_allocation_company() FROM anon;
REVOKE EXECUTE ON FUNCTION validate_payment_allocation_company() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION verify_company_access(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION verify_company_access(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION void_invoice(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION void_invoice(uuid) FROM PUBLIC;

