
import { ThemePreset } from './types';

export const THEME_PRESETS: ThemePreset[] = [
  // ═══════════════════════════════════════════════════════════
  // ✨ باقات برو الاحترافية — Premium Pro
  // ═══════════════════════════════════════════════════════════
  {
    id: 'emerald-pro',
    name: 'زمردي احترافي',
    description: 'مزيج من ألوان الغابات الزمردية العميقة. هدوء وفخامة في كل وضع.',
    colors: ['#059669', '#10b981', '#ecfdf5'],
    previewColor: '#059669',
    accent: '#059669',
    isDark: false,
    category: 'premium',
    emoji: '🌿',
    cssVars: {
      '--app-bg': '#f0fdf4',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dcfce7',
      '--app-border': '#bbf7d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    },
    light: {
      '--app-bg': '#f0fdf4',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dcfce7',
      '--app-border': '#bbf7d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    },
    dark: {
      '--app-bg': '#020617',
      '--app-surface': '#0f172a',
      '--app-surface-hover': '#1e293b',
      '--app-border': '#1e293b',
      '--app-text': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#10b981',
    }
  },
  {
    id: 'sapphire-pro',
    name: 'ياقوت أزرق احترافي',
    description: 'أزرق كحلي عميق مع لمسات فضية باردة. للمكاتب الرسمية والمؤسسات.',
    colors: ['#1e40af', '#3b82f6', '#eff6ff'],
    previewColor: '#1e40af',
    accent: '#1e40af',
    isDark: false,
    category: 'premium',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#1e40af',
    },
    light: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#1e40af',
    },
    dark: {
      '--app-bg': '#0a0f1e',
      '--app-surface': '#141b2d',
      '--app-surface-hover': '#1e293b',
      '--app-border': '#1e293b',
      '--app-text': '#e2e8f0',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#3b82f6',
    }
  },
  {
    id: 'amethyst-pro',
    name: 'أرجواني ملكي احترافي',
    description: 'أناقة اللافندر الفاخر مع تدرجات رويال. لمسة إبداعية متميزة.',
    colors: ['#6d28d9', '#8b5cf6', '#f5f3ff'],
    previewColor: '#6d28d9',
    accent: '#6d28d9',
    isDark: false,
    category: 'premium',
    emoji: '🔮',
    cssVars: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#2e1065',
      '--app-text-secondary': '#6d28d9',
      '--accent': '#6d28d9',
    },
    light: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#2e1065',
      '--app-text-secondary': '#6d28d9',
      '--accent': '#6d28d9',
    },
    dark: {
      '--app-bg': '#0f0a1f',
      '--app-surface': '#1a1229',
      '--app-surface-hover': '#251a38',
      '--app-border': '#3d2a52',
      '--app-text': '#f3e8ff',
      '--app-text-secondary': '#c084fc',
      '--accent': '#a855f7',
    }
  },
  {
    id: 'obsidian-pro',
    name: 'أوبسيديان فاخر',
    description: 'تباين عالٍ يجمع بين الفولاذ المصقول والأسود الفاخر. لمحبي الحداثة.',
    colors: ['#0f172a', '#334155', '#f8fafc'],
    previewColor: '#0f172a',
    accent: '#0f172a',
    isDark: false,
    category: 'premium',
    emoji: '🖤',
    cssVars: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#cbd5e1',
      '--app-text': '#020617',
      '--app-text-secondary': '#475569',
      '--accent': '#0f172a',
    },
    light: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#cbd5e1',
      '--app-text': '#020617',
      '--app-text-secondary': '#475569',
      '--accent': '#0f172a',
    },
    dark: {
      '--app-bg': '#020617',
      '--app-surface': '#0a0a0a',
      '--app-surface-hover': '#171717',
      '--app-border': '#262626',
      '--app-text': '#fafafa',
      '--app-text-secondary': '#a3a3a3',
      '--accent': '#ffffff',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🏛️ كلاسيكي — Classic
  // ═══════════════════════════════════════════════════════════
  {
    id: 'clean-white',
    name: 'النظام الناصع',
    description: 'تصميم رسمي نظيف يركز على سهولة القراءة والوضوح التام.',
    colors: ['#3b82f6', '#60a5fa', '#f8fafc'],
    previewColor: '#ffffff',
    accent: '#3b82f6',
    isDark: false,
    category: 'classic',
    emoji: '⚪',
    cssVars: {
      '--app-bg': '#f4f6f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#eef1f6',
      '--app-border': '#d5dbe5',
      '--app-text': '#1a2332',
      '--app-text-secondary': '#5a6a7e',
      '--accent': '#3b82f6',
    }
  },
  {
    id: 'midnight-ocean',
    name: 'عمق المحيط',
    description: 'تباين مريح للعين في الإضاءة المنخفضة مع لمسات زرقاء.',
    colors: ['#38bdf8', '#3b82f6', '#1e293b'],
    previewColor: '#0f172a',
    accent: '#38bdf8',
    isDark: true,
    category: 'classic',
    emoji: '🌊',
    cssVars: {
      '--app-bg': '#0c1524',
      '--app-surface': '#141f33',
      '--app-surface-hover': '#1c2d48',
      '--app-border': '#253854',
      '--app-text': '#e8edf5',
      '--app-text-secondary': '#8da0be',
      '--accent': '#38bdf8',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🏜️ بيج — Beige & Warm Tones
  // ═══════════════════════════════════════════════════════════
  {
    id: 'warm-sand',
    name: 'رمال دافئة',
    description: 'ألوان الرمال الذهبية مع درجات البيج الكلاسيكية. هدوء وأناقة.',
    colors: ['#d4a574', '#c4956a', '#faf5ef'],
    previewColor: '#fdf8f0',
    accent: '#c4956a',
    isDark: false,
    category: 'beige',
    emoji: '🏜️',
    cssVars: {
      '--app-bg': '#f6f0e6',
      '--app-surface': '#fdf8f0',
      '--app-surface-hover': '#f0e5d5',
      '--app-border': '#ddd0be',
      '--app-text': '#3a2c1e',
      '--app-text-secondary': '#7a6545',
      '--accent': '#c4956a',
    }
  },
  {
    id: 'desert-cream',
    name: 'كريم صحراوي',
    description: 'لون كريمي ناعم مع لمسات ذهبية فاخرة. مثالي للاستخدام الطويل.',
    colors: ['#c8960e', '#daa520', '#faebd7'],
    previewColor: '#faf0e6',
    accent: '#c8960e',
    isDark: false,
    category: 'beige',
    emoji: '🍶',
    cssVars: {
      '--app-bg': '#f5ecde',
      '--app-surface': '#fdf5ec',
      '--app-surface-hover': '#f0e2cc',
      '--app-border': '#ddd0b5',
      '--app-text': '#352510',
      '--app-text-secondary': '#7a6338',
      '--accent': '#c8960e',
    }
  },
  {
    id: 'champagne-gold',
    name: 'ذهب الشامبانيا',
    description: 'أناقة فاخرة بلون الشامبانيا الذهبي. للمظهر الاحترافي الراقي.',
    colors: ['#c9a96e', '#b8975a', '#f7f1e8'],
    previewColor: '#f5eedf',
    accent: '#b8975a',
    isDark: false,
    category: 'beige',
    emoji: '🥂',
    cssVars: {
      '--app-bg': '#f2eadb',
      '--app-surface': '#f9f3e8',
      '--app-surface-hover': '#ece2cf',
      '--app-border': '#d8ccb2',
      '--app-text': '#33291a',
      '--app-text-secondary': '#756548',
      '--accent': '#b8975a',
    }
  },
  {
    id: 'mocha-latte',
    name: 'موكا لاتيه',
    description: 'دفء القهوة بالحليب مع تدرجات بنية كريمية. مريح للعين.',
    colors: ['#8b6f47', '#a0845c', '#f3ece0'],
    previewColor: '#f0e8d8',
    accent: '#8b6f47',
    isDark: false,
    category: 'beige',
    emoji: '☕',
    cssVars: {
      '--app-bg': '#ece3d2',
      '--app-surface': '#f5efe2',
      '--app-surface-hover': '#e5d9c6',
      '--app-border': '#cfc0a8',
      '--app-text': '#2e2215',
      '--app-text-secondary': '#6b5638',
      '--accent': '#8b6f47',
    }
  },
  {
    id: 'rose-beige',
    name: 'بيج وردي',
    description: 'مزيج ناعم من البيج والوردي الفاتح. لمسة أنثوية عصرية.',
    colors: ['#c48b80', '#d4a090', '#faf0ee'],
    previewColor: '#fdf5f3',
    accent: '#c07060',
    isDark: false,
    category: 'beige',
    emoji: '🌸',
    cssVars: {
      '--app-bg': '#f6ece9',
      '--app-surface': '#fdf5f3',
      '--app-surface-hover': '#f0e3de',
      '--app-border': '#e0cdc7',
      '--app-text': '#3a2220',
      '--app-text-secondary': '#8b5852',
      '--accent': '#c07060',
    }
  },
  {
    id: 'midnight-caramel',
    name: 'كراميل ليلي',
    description: 'وضع مظلم دافئ بلون الكراميل البني. أناقة ليلية مميزة.',
    colors: ['#e8b878', '#d4a060', '#2c1810'],
    previewColor: '#1a1008',
    accent: '#e8b878',
    isDark: true,
    category: 'beige',
    emoji: '🌙',
    cssVars: {
      '--app-bg': '#13100a',
      '--app-surface': '#1e1810',
      '--app-surface-hover': '#2d2418',
      '--app-border': '#40321e',
      '--app-text': '#f0e4d0',
      '--app-text-secondary': '#b89868',
      '--accent': '#e8b878',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 👑 ملكي — Royal & Luxury
  // ═══════════════════════════════════════════════════════════
  {
    id: 'royal-navy',
    name: 'أزرق ملكي',
    description: 'أزرق داكن فاخر مع لمسات ذهبية. أناقة الملوك والقصور.',
    colors: ['#fbbf24', '#c9a96e', '#1a2744'],
    previewColor: '#0f1a30',
    accent: '#f0b440',
    isDark: true,
    category: 'royal',
    emoji: '👑',
    cssVars: {
      '--app-bg': '#0c1525',
      '--app-surface': '#142035',
      '--app-surface-hover': '#1c2d48',
      '--app-border': '#263d5c',
      '--app-text': '#eae2d0',
      '--app-text-secondary': '#a09478',
      '--accent': '#f0b440',
    }
  },
  {
    id: 'royal-purple',
    name: 'بنفسجي ملكي',
    description: 'بنفسجي فاخر مع تدرجات ذهبية. فخامة ملكية راقية.',
    colors: ['#a78bfa', '#8b5cf6', '#f5f0ff'],
    previewColor: '#faf5ff',
    accent: '#8b5cf6',
    isDark: false,
    category: 'royal',
    emoji: '💜',
    cssVars: {
      '--app-bg': '#f0e8ff',
      '--app-surface': '#f9f5ff',
      '--app-surface-hover': '#e8daff',
      '--app-border': '#d4c0f0',
      '--app-text': '#2a1550',
      '--app-text-secondary': '#6d48a8',
      '--accent': '#8b5cf6',
    }
  },
  {
    id: 'royal-purple-dark',
    name: 'ليل بنفسجي',
    description: 'وضع مظلم بنفسجي ملكي. فخامة عميقة مع وضوح تام.',
    colors: ['#c084fc', '#a855f7', '#1a0830'],
    previewColor: '#120520',
    accent: '#c084fc',
    isDark: true,
    category: 'royal',
    emoji: '🔮',
    cssVars: {
      '--app-bg': '#0e0820',
      '--app-surface': '#18102e',
      '--app-surface-hover': '#241840',
      '--app-border': '#342458',
      '--app-text': '#e8daf5',
      '--app-text-secondary': '#a080cc',
      '--accent': '#c084fc',
    }
  },
  {
    id: 'royal-emerald',
    name: 'زمردي ملكي',
    description: 'أخضر زمردي ملكي مع ذهب. رمز الرخاء والثروة.',
    colors: ['#fbbf24', '#10b981', '#f0faf5'],
    previewColor: '#f0fdf4',
    accent: '#0d9668',
    isDark: false,
    category: 'royal',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#ecf7f0',
      '--app-surface': '#f5fdf8',
      '--app-surface-hover': '#e0f2e8',
      '--app-border': '#c0deca',
      '--app-text': '#0f2d1e',
      '--app-text-secondary': '#3d7a58',
      '--accent': '#0d9668',
    }
  },
  {
    id: 'royal-burgundy',
    name: 'عنابي ملكي',
    description: 'أحمر بورغندي فاخر. لون النبيذ الملكي مع ذهب دافئ.',
    colors: ['#f59e0b', '#dc2626', '#1c0808'],
    previewColor: '#140505',
    accent: '#e8a040',
    isDark: true,
    category: 'royal',
    emoji: '🍷',
    cssVars: {
      '--app-bg': '#10060a',
      '--app-surface': '#1c0c12',
      '--app-surface-hover': '#2a141e',
      '--app-border': '#401828',
      '--app-text': '#f0dcd0',
      '--app-text-secondary': '#c08868',
      '--accent': '#e8a040',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 📊 محاسبي — Accounting & Finance
  // ═══════════════════════════════════════════════════════════
  {
    id: 'finance-blue',
    name: 'أزرق مالي',
    description: 'الأزرق المصرفي الرسمي. احترافي وموثوق للأنظمة المالية.',
    colors: ['#1d4ed8', '#3b82f6', '#eff6ff'],
    previewColor: '#f0f6ff',
    accent: '#1d4ed8',
    isDark: false,
    category: 'accounting',
    emoji: '🏦',
    cssVars: {
      '--app-bg': '#edf2fd',
      '--app-surface': '#f5f8ff',
      '--app-surface-hover': '#dce6f8',
      '--app-border': '#bccee8',
      '--app-text': '#0f1d3a',
      '--app-text-secondary': '#405880',
      '--accent': '#1d4ed8',
    }
  },
  {
    id: 'finance-green',
    name: 'أخضر مالي',
    description: 'أخضر الأرباح والنمو. يوحي بالاستقرار المالي والنجاح.',
    colors: ['#16a34a', '#22c55e', '#f0fdf4'],
    previewColor: '#f0fdf4',
    accent: '#16a34a',
    isDark: false,
    category: 'accounting',
    emoji: '💰',
    cssVars: {
      '--app-bg': '#edf8f0',
      '--app-surface': '#f5fdf7',
      '--app-surface-hover': '#dcf2e2',
      '--app-border': '#b8dec5',
      '--app-text': '#0c2a15',
      '--app-text-secondary': '#326845',
      '--accent': '#16a34a',
    }
  },
  {
    id: 'finance-dark',
    name: 'ليل مالي',
    description: 'وضع مظلم احترافي للمحاسبين. أرقام واضحة وتباين ممتاز.',
    colors: ['#4ade80', '#22c55e', '#0a1a10'],
    previewColor: '#0a1a10',
    accent: '#4ade80',
    isDark: true,
    category: 'accounting',
    emoji: '📈',
    cssVars: {
      '--app-bg': '#080f0c',
      '--app-surface': '#101c15',
      '--app-surface-hover': '#1a2e22',
      '--app-border': '#243d2e',
      '--app-text': '#d8f5e2',
      '--app-text-secondary': '#70c090',
      '--accent': '#4ade80',
    }
  },
  {
    id: 'finance-slate',
    name: 'رمادي رسمي',
    description: 'رمادي محايد احترافي. مثالي للتدقيق والتقارير المالية.',
    colors: ['#475569', '#64748b', '#f1f5f9'],
    previewColor: '#f8fafc',
    accent: '#475569',
    isDark: false,
    category: 'accounting',
    emoji: '📋',
    cssVars: {
      '--app-bg': '#eef1f5',
      '--app-surface': '#f8fafc',
      '--app-surface-hover': '#e2e8f0',
      '--app-border': '#c8d0dc',
      '--app-text': '#141c28',
      '--app-text-secondary': '#4a5568',
      '--accent': '#475569',
    }
  },
  {
    id: 'finance-teal',
    name: 'تركوازي مالي',
    description: 'تركوازي عصري للأنظمة المالية الحديثة. حيوية واحترافية.',
    colors: ['#0d9488', '#14b8a6', '#f0fdfa'],
    previewColor: '#f0fdfa',
    accent: '#0d9488',
    isDark: false,
    category: 'accounting',
    emoji: '💹',
    cssVars: {
      '--app-bg': '#e8f8f5',
      '--app-surface': '#f0fdfa',
      '--app-surface-hover': '#d8f0ec',
      '--app-border': '#b0dcd5',
      '--app-text': '#0a2824',
      '--app-text-secondary': '#2d706a',
      '--accent': '#0d9488',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🌿 طبيعي — Nature
  // ═══════════════════════════════════════════════════════════
  {
    id: 'emerald-forest',
    name: 'غابة زمردية',
    description: 'أخضر زمردي غني. إحساس بالطبيعة والانتعاش.',
    colors: ['#059669', '#10b981', '#ecfdf5'],
    previewColor: '#f0fdf4',
    accent: '#059669',
    isDark: false,
    category: 'nature',
    emoji: '🌿',
    cssVars: {
      '--app-bg': '#ebf7f0',
      '--app-surface': '#f5fdf8',
      '--app-surface-hover': '#daf0e4',
      '--app-border': '#b8dcc8',
      '--app-text': '#0e2a1c',
      '--app-text-secondary': '#367a55',
      '--accent': '#059669',
    }
  },
  {
    id: 'deep-forest',
    name: 'ليل الغابة',
    description: 'أخضر غامق غني مع ظلال الليل. هدوء واحترافية.',
    colors: ['#34d399', '#10b981', '#0f2922'],
    previewColor: '#0a1f17',
    accent: '#34d399',
    isDark: true,
    category: 'nature',
    emoji: '🌲',
    cssVars: {
      '--app-bg': '#080f0c',
      '--app-surface': '#10201a',
      '--app-surface-hover': '#183028',
      '--app-border': '#204038',
      '--app-text': '#d0f0e0',
      '--app-text-secondary': '#60b88a',
      '--accent': '#34d399',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🔥 جريء — Bold
  // ═══════════════════════════════════════════════════════════
  {
    id: 'crimson-dark',
    name: 'قرمزي مظلم',
    description: 'أحمر قرمزي عميق في وضع مظلم. قوة وتميّز.',
    colors: ['#f87171', '#ef4444', '#1c0a0a'],
    previewColor: '#170808',
    accent: '#f87171',
    isDark: true,
    category: 'bold',
    emoji: '🔥',
    cssVars: {
      '--app-bg': '#100606',
      '--app-surface': '#1c0c0c',
      '--app-surface-hover': '#2c1414',
      '--app-border': '#401818',
      '--app-text': '#f5d8d8',
      '--app-text-secondary': '#d07070',
      '--accent': '#f87171',
    }
  },
  {
    id: 'sunset-orange',
    name: 'غروب برتقالي',
    description: 'ألوان الغروب الدافئة. طاقة إيجابية وحيوية.',
    colors: ['#f97316', '#fb923c', '#fff7ed'],
    previewColor: '#fff7ed',
    accent: '#ea6c0c',
    isDark: false,
    category: 'bold',
    emoji: '🌅',
    cssVars: {
      '--app-bg': '#fef0e0',
      '--app-surface': '#fff8ef',
      '--app-surface-hover': '#fde8d0',
      '--app-border': '#f0d0a8',
      '--app-text': '#3a1e08',
      '--app-text-secondary': '#8a5a28',
      '--accent': '#ea6c0c',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🏢 شركة — Corporate & Modern
  // ═══════════════════════════════════════════════════════════
  {
    id: 'corporate-slate',
    name: 'شركة رمادية',
    description: 'رمادي حديث أنيق للشركات الناشئة والتقنية.',
    colors: ['#6366f1', '#818cf8', '#eef2ff'],
    previewColor: '#eef2ff',
    accent: '#6366f1',
    isDark: false,
    category: 'corporate',
    emoji: '🏢',
    cssVars: {
      '--app-bg': '#eef2ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#e0e7ff',
      '--app-border': '#c7d2fe',
      '--app-text': '#1e1b4b',
      '--app-text-secondary': '#4338ca',
      '--accent': '#6366f1',
    }
  },
  {
    id: 'corporate-slate-dark',
    name: 'ليل الشركة',
    description: 'وضع مظلم أنيق للشركات التقنية الحديثة.',
    colors: ['#818cf8', '#6366f1', '#1e1b4b'],
    previewColor: '#1e1b4b',
    accent: '#818cf8',
    isDark: true,
    category: 'corporate',
    emoji: '💻',
    cssVars: {
      '--app-bg': '#0f0f1a',
      '--app-surface': '#1a1a2e',
      '--app-surface-hover': '#252542',
      '--app-border': '#363654',
      '--app-text': '#e0e7ff',
      '--app-text-secondary': '#818cf8',
      '--accent': '#818cf8',
    }
  },
  {
    id: 'modern-teal',
    name: 'تركواز عصري',
    description: 'تركواز حداثي نظيف للتطبيقات المالية.',
    colors: ['#14b8a6', '#2dd4bf', '#f0fdfa'],
    previewColor: '#f0fdfa',
    accent: '#0d9488',
    isDark: false,
    category: 'corporate',
    emoji: '🎯',
    cssVars: {
      '--app-bg': '#f0fdfa',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ccfbf1',
      '--app-border': '#99f6e4',
      '--app-text': '#042f2e',
      '--app-text-secondary': '#115e59',
      '--accent': '#0d9488',
    }
  },
  {
    id: 'modern-cyan',
    name: 'سيان حديث',
    description: 'أزرق سيان نابض بالحياة للتطبيقات الحيوية.',
    colors: ['#06b6d4', '#22d3ee', '#ecfeff'],
    previewColor: '#ecfeff',
    accent: '#0891b2',
    isDark: false,
    category: 'corporate',
    emoji: '💠',
    cssVars: {
      '--app-bg': '#ecfeff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#cffafe',
      '--app-border': '#a5f3fc',
      '--app-text': '#083344',
      '--app-text-secondary': '#155e75',
      '--accent': '#0891b2',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🌙 ليلي — Night Themes
  // ═══════════════════════════════════════════════════════════
  {
    id: 'night-amethyst',
    name: 'ليلي ياقوتي',
    description: 'ياقوت أرجواني داكن مع بريق星光.',
    colors: ['#a855f7', '#c084fc', '#2e1065'],
    previewColor: '#2e1065',
    accent: '#a855f7',
    isDark: true,
    category: 'night',
    emoji: '✨',
    cssVars: {
      '--app-bg': '#0f0a1f',
      '--app-surface': '#1a1229',
      '--app-surface-hover': '#251a38',
      '--app-border': '#3d2a52',
      '--app-text': '#f3e8ff',
      '--app-text-secondary': '#c084fc',
      '--accent': '#a855f7',
    }
  },
  {
    id: 'night-sapphire',
    name: 'ليلي ياقوت أزرق',
    description: 'ياقوت أزرق داكن مع لمسات فيروزية.',
    colors: ['#38bdf8', '#7dd3fc', '#0c4a6e'],
    previewColor: '#0c4a6e',
    accent: '#38bdf8',
    isDark: true,
    category: 'night',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#071a2e',
      '--app-surface': '#0f2847',
      '--app-surface-hover': '#163660',
      '--app-border': '#1e4976',
      '--app-text': '#e0f2fe',
      '--app-text-secondary': '#7dd3fc',
      '--accent': '#38bdf8',
    }
  },
  {
    id: 'night-gold',
    name: 'ليل ذهبي',
    description: 'ذهب داكن مع لمسات برتقالية ليلية.',
    colors: ['#fbbf24', '#fcd34d', '#451a03'],
    previewColor: '#451a03',
    accent: '#fbbf24',
    isDark: true,
    category: 'night',
    emoji: '🌟',
    cssVars: {
      '--app-bg': '#1a1205',
      '--app-surface': '#2a1c08',
      '--app-surface-hover': '#3d2810',
      '--app-border': '#5c3d18',
      '--app-text': '#fef3c7',
      '--app-text-secondary': '#fbbf24',
      '--accent': '#fbbf24',
    }
  },
  {
    id: 'night-rose',
    name: 'ليلي وردي',
    description: 'وردي داكن أنيق مع تدرجات أرجوانية.',
    colors: ['#fb7185', '#fb923c', '#881337'],
    previewColor: '#881337',
    accent: '#fb7185',
    isDark: true,
    category: 'night',
    emoji: '🌹',
    cssVars: {
      '--app-bg': '#1a0812',
      '--app-surface': '#2d101c',
      '--app-surface-hover': '#401828',
      '--app-border': '#5c2036',
      '--app-text': '#ffe4e6',
      '--app-text-secondary': '#fb7185',
      '--accent': '#fb7185',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🌸 موسمي — Seasonal
  // ═══════════════════════════════════════════════════════════
  {
    id: 'spring-pink',
    name: 'وردي ربيعي',
    description: 'وردي primaveral نابض بالحياة والأمل.',
    colors: ['#ec4899', '#f472b6', '#fdf2f8'],
    previewColor: '#fdf2f8',
    accent: '#db2777',
    isDark: false,
    category: 'seasonal',
    emoji: '🌸',
    cssVars: {
      '--app-bg': '#fdf2f8',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fce7f3',
      '--app-border': '#fbcfe8',
      '--app-text': '#831843',
      '--app-text-secondary': '#be185d',
      '--accent': '#db2777',
    }
  },
  {
    id: 'summer-cyan',
    name: 'سيان صيفي',
    description: 'أزرق صيفي منعش مع لمسات فيروزية.',
    colors: ['#06b6d4', '#22d3ee', '#ecfeff'],
    previewColor: '#ecfeff',
    accent: '#0891b2',
    isDark: false,
    category: 'seasonal',
    emoji: '☀️',
    cssVars: {
      '--app-bg': '#ecfeff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#cffafe',
      '--app-border': '#a5f3fc',
      '--app-text': '#083344',
      '--app-text-secondary': '#155e75',
      '--accent': '#0891b2',
    }
  },
  {
    id: 'autumn-orange',
    name: 'برتقالي خريفي',
    description: 'برتقالي دافئ بألوان أوراق الخريف.',
    colors: ['#ea580c', '#f97316', '#fff7ed'],
    previewColor: '#fff7ed',
    accent: '#c2410c',
    isDark: false,
    category: 'seasonal',
    emoji: '🍂',
    cssVars: {
      '--app-bg': '#fff7ed',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ffedd5',
      '--app-border': '#fed7aa',
      '--app-text': '#7c2d12',
      '--app-text-secondary': '#c2410c',
      '--accent': '#c2410c',
    }
  },
  {
    id: 'winter-blue',
    name: 'أزرق شتوي',
    description: 'أزرق بارد مع لمسات ثلجية.',
    colors: ['#3b82f6', '#60a5fa', '#eff6ff'],
    previewColor: '#eff6ff',
    accent: '#2563eb',
    isDark: false,
    category: 'seasonal',
    emoji: '❄️',
    cssVars: {
      '--app-bg': '#eff6ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dbeafe',
      '--app-border': '#bfdbfe',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#2563eb',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 🎨 فني — Artistic
  // ═══════════════════════════════════════════════════════════
  {
    id: 'artist-indigo',
    name: 'أنديغو فني',
    description: 'أنديغو عميق مع لمسات بنفسجية.',
    colors: ['#6366f1', '#818cf8', '#e0e7ff'],
    previewColor: '#e0e7ff',
    accent: '#4f46e5',
    isDark: false,
    category: 'artistic',
    emoji: '🎨',
    cssVars: {
      '--app-bg': '#e0e7ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#c7d2fe',
      '--app-border': '#a5b4fc',
      '--app-text': '#312e81',
      '--app-text-secondary': '#4f46e5',
      '--accent': '#4f46e5',
    }
  },
  {
    id: 'artist-lavender',
    name: 'لافندر فني',
    description: 'خزامي ناعم مع لمسات فيروزية.',
    colors: ['#a78bfa', '#c4b5fd', '#f5f3ff'],
    previewColor: '#f5f3ff',
    accent: '#8b5cf6',
    isDark: false,
    category: 'artistic',
    emoji: '🖌️',
    cssVars: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#4c1d95',
      '--app-text-secondary': '#7c3aed',
      '--accent': '#8b5cf6',
    }
  },
  {
    id: 'minimal-gray',
    name: 'رمادي بسيط',
    description: 'بسيط ونظيف مع لمسات أرجوانية خفيفة.',
    colors: ['#a1a1aa', '#71717a', '#fafafa'],
    previewColor: '#fafafa',
    accent: '#71717a',
    isDark: false,
    category: 'artistic',
    emoji: '⬜',
    cssVars: {
      '--app-bg': '#fafafa',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f4f4f5',
      '--app-border': '#e4e4e7',
      '--app-text': '#27272a',
      '--app-text-secondary': '#52525b',
      '--accent': '#71717a',
    }
  },

  // ═══════════════════════════════════════════════════════════
  // 💼 قطاعي — Industry-Specific
  // ═══════════════════════════════════════════════════════════
  {
    id: 'health-medical',
    name: 'طبي صحي',
    description: 'أخضر طبي هادئ للمنشآت الصحية.',
    colors: ['#10b981', '#34d399', '#ecfdf5'],
    previewColor: '#ecfdf5',
    accent: '#059669',
    isDark: false,
    category: 'industry',
    emoji: '🏥',
    cssVars: {
      '--app-bg': '#ecfdf5',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#d1fae5',
      '--app-border': '#a7f3d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    }
  },
  {
    id: 'food-restaurant',
    name: 'مطاعم وطعام',
    description: 'برتقالي دافئ للمطاعم والوجبات.',
    colors: ['#f59e0b', '#fbbf24', '#fffbeb'],
    previewColor: '#fffbeb',
    accent: '#d97706',
    isDark: false,
    category: 'industry',
    emoji: '🍽️',
    cssVars: {
      '--app-bg': '#fffbeb',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fef3c7',
      '--app-border': '#fde68a',
      '--app-text': '#78350f',
      '--app-text-secondary': '#b45309',
      '--accent': '#d97706',
    }
  },
  {
    id: 'education-school',
    name: 'تعليم ومدرسة',
    description: 'أزرق تعليمي هادئ للمدارس.',
    colors: ['#3b82f6', '#60a5fa', '#eff6ff'],
    previewColor: '#eff6ff',
    accent: '#2563eb',
    isDark: false,
    category: 'industry',
    emoji: '📚',
    cssVars: {
      '--app-bg': '#eff6ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dbeafe',
      '--app-border': '#bfdbfe',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#2563eb',
    }
  },
  {
    id: 'automotive-car',
    name: 'سيارات و قطع غيار',
    description: 'أزرق داكن احترافي لصناعة السيارات.',
    colors: ['#1d4ed8', '#3b82f6', '#dbeafe'],
    previewColor: '#dbeafe',
    accent: '#1e40af',
    isDark: false,
    category: 'industry',
    emoji: '🚗',
    cssVars: {
      '--app-bg': '#dbeafe',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#bfdbfe',
      '--app-border': '#93c5fd',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#1e40af',
    }
  },
  {
    id: 'crystal-glass',
    name: 'كريستال زجاجي',
    description: 'شفافية ناصعة مع بلور ناعم. مظهر عصري وخفيف جداً.',
    colors: ['#ffffff', '#f0f9ff', '#e0f2fe'],
    previewColor: '#ffffff',
    accent: '#3b82f6',
    isDark: false,
    category: 'glass',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#f8fafc',
      '--app-surface': 'rgba(255, 255, 255, 0.7)',
      '--app-surface-hover': 'rgba(255, 255, 255, 0.9)',
      '--app-border': 'rgba(255, 255, 255, 0.5)',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#3b82f6',
    }
  },
  {
    id: 'frosted-obsidian',
    name: 'أوبسيديان مثلج',
    description: 'زجاج داكن مع تأثير الثلج. فخامة وهدوء في الوضع الليلي.',
    colors: ['#0f172a', '#1e293b', '#334155'],
    previewColor: '#0f172a',
    accent: '#818cf8',
    isDark: true,
    category: 'glass',
    emoji: '🌌',
    cssVars: {
      '--app-bg': '#020617',
      '--app-surface': 'rgba(15, 23, 42, 0.7)',
      '--app-surface-hover': 'rgba(30, 41, 59, 0.8)',
      '--app-border': 'rgba(255, 255, 255, 0.1)',
      '--app-text': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#818cf8',
    }
  },
  {
    id: 'aurora-glass',
    name: 'أورورا زجاجي',
    description: 'تدرجات ألوان الشفق القطبي خلف زجاج شفاف. إبداع وحيوية.',
    colors: ['#4f46e5', '#ec4899', '#06b6d4'],
    previewColor: '#4f46e5',
    accent: '#6366f1',
    isDark: false,
    category: 'glass',
    emoji: '🌈',
    cssVars: {
      '--app-bg': 'linear-gradient(135deg, #f5f3ff 0%, #fdf2f8 50%, #ecfeff 100%)',
      '--app-surface': 'rgba(255, 255, 255, 0.6)',
      '--app-surface-hover': 'rgba(255, 255, 255, 0.8)',
      '--app-border': 'rgba(255, 255, 255, 0.4)',
      '--app-text': '#1e1b4b',
      '--app-text-secondary': '#4338ca',
      '--accent': '#6366f1',
    }
  },
  {
    id: 'bento-pro',
    name: 'بينتو احترافي',
    description: 'تقسيمات هندسية دقيقة مع تباين عالي. مثالي للوحات البيانات المعقدة.',
    colors: ['#0f172a', '#f1f5f9', '#3b82f6'],
    previewColor: '#f1f5f9',
    accent: '#2563eb',
    isDark: false,
    category: 'bento',
    emoji: '📊',
    cssVars: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#64748b',
      '--accent': '#2563eb',
    }
  },
];

// تصنيفات الثيمات مع الأسماء العربية
export const THEME_CATEGORIES = {
  premium: { label: 'باقات برو الاحترافية', emoji: '✨', description: 'ثيمات ذكية تدعم الوضعين الليلي والنهاري تلقائياً' },
  classic: { label: 'كلاسيكي', emoji: '🏛️', description: 'التصاميم الرسمية التقليدية' },
  beige: { label: 'بيج ودافئ', emoji: '🏜️', description: 'ألوان الرمال والكريم والكراميل' },
  royal: { label: 'ملكي فاخر', emoji: '👑', description: 'ألوان ملكية فخمة مع لمسات ذهبية' },
  accounting: { label: 'محاسبي', emoji: '📊', description: 'ألوان احترافية للأنظمة المالية' },
  nature: { label: 'طبيعي', emoji: '🌿', description: 'ألوان الطبيعة والغابات' },
  bold: { label: 'جريء', emoji: '🔥', description: 'ألوان قوية ومميزة' },
  corporate: { label: 'شركة حديث', emoji: '🏢', description: 'ألوان للشركات الناشئة والتقنية' },
  night: { label: 'ليلي', emoji: '🌙', description: 'ثيمات ليلية داكنة وأنيقة' },
  seasonal: { label: 'موسيقي', emoji: '🌸', description: 'ألوان موسمية متغيرة' },
  artistic: { label: 'فني', emoji: '🎨', description: 'ألوان فنية وإبداعية' },
  industry: { label: 'قطاعي', emoji: '🏭', description: 'ألوان متخصصة للصناعات المختلفة' },
  glass: { label: 'زجاجي (Glass)', emoji: '🪟', description: 'تأثيرات الشفافية والبلور العصرية' },
  bento: { label: 'بينتو (Bento)', emoji: '🍱', description: 'تقسيمات شبكية احترافية للبيانات' },
} as const;
