import type { ThemePreset } from '../types';
import { normalize } from './normalize';

export const CORPORATE_PRESETS: ThemePreset[] = [
  // ══════════════════════════════════════════════════════════════════════
  // محاسبي — Accounting & Finance
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'finance-blue',
    name: 'أزرق مالي',
    description: 'الأزرق المصرفي الرسمي. احترافي وموثوق للأنظمة المالية.',
    colors: ['#1d4ed8', '#3b82f6', '#eff6ff'],
    previewColor: '#f0f6ff',
    accent: '#1d4ed8',
    isDark: false,
    category: 'accounting',
    emoji: '🏦',
    cssVars: {
      '--app-bg': '#edf2fd',
      '--app-surface': '#f5f8ff',
      '--app-surface-hover': '#dce6f8',
      '--app-border': '#bccee8',
      '--app-text': '#0f1d3a',
      '--app-text-secondary': '#405880',
      '--accent': '#1d4ed8',
    },
  }),
  normalize({
    id: 'finance-green',
    name: 'أخضر مالي',
    description: 'أخضر الأرباح والنمو. يوحي بالاستقرار المالي والنجاح.',
    colors: ['#16a34a', '#22c55e', '#f0fdf4'],
    previewColor: '#f0fdf4',
    accent: '#16a34a',
    isDark: false,
    category: 'accounting',
    emoji: '💰',
    cssVars: {
      '--app-bg': '#edf8f0',
      '--app-surface': '#f5fdf7',
      '--app-surface-hover': '#dcf2e2',
      '--app-border': '#b8dec5',
      '--app-text': '#0c2a15',
      '--app-text-secondary': '#326845',
      '--accent': '#16a34a',
    },
  }),
  normalize({
    id: 'finance-dark',
    name: 'ليل مالي',
    description: 'وضع مظلم احترافي للمحاسبين. أرقام واضحة وتباين ممتاز.',
    colors: ['#4ade80', '#22c55e', '#0a1a10'],
    previewColor: '#0a1a10',
    accent: '#4ade80',
    isDark: true,
    category: 'accounting',
    emoji: '📈',
    cssVars: {
      '--app-bg': '#080f0c',
      '--app-surface': '#101c15',
      '--app-surface-hover': '#1a2e22',
      '--app-border': '#243d2e',
      '--app-text': '#d8f5e2',
      '--app-text-secondary': '#70c090',
      '--accent': '#4ade80',
    },
  }),
  normalize({
    id: 'finance-slate',
    name: 'رمادي رسمي',
    description: 'رمادي محايد احترافي. مثالي للتدقيق والتقارير المالية.',
    colors: ['#475569', '#64748b', '#f1f5f9'],
    previewColor: '#f8fafc',
    accent: '#475569',
    isDark: false,
    category: 'accounting',
    emoji: '📋',
    cssVars: {
      '--app-bg': '#eef1f5',
      '--app-surface': '#f8fafc',
      '--app-surface-hover': '#e2e8f0',
      '--app-border': '#c8d0dc',
      '--app-text': '#141c28',
      '--app-text-secondary': '#4a5568',
      '--accent': '#475569',
    },
  }),
  normalize({
    id: 'finance-teal',
    name: 'تركوازي مالي',
    description: 'تركوازي عصري للأنظمة المالية الحديثة. حيوية واحترافية.',
    colors: ['#0d9488', '#14b8a6', '#f0fdfa'],
    previewColor: '#f0fdfa',
    accent: '#0d9488',
    isDark: false,
    category: 'accounting',
    emoji: '💹',
    cssVars: {
      '--app-bg': '#e8f8f5',
      '--app-surface': '#f0fdfa',
      '--app-surface-hover': '#d8f0ec',
      '--app-border': '#b0dcd5',
      '--app-text': '#0a2824',
      '--app-text-secondary': '#2d706a',
      '--accent': '#0d9488',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // طبيعي — Nature
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'emerald-forest',
    name: 'غابة زمردية',
    description: 'أخضر زمردي غني. إحساس بالطبيعة والانتعاش.',
    colors: ['#059669', '#10b981', '#ecfdf5'],
    previewColor: '#f0fdf4',
    accent: '#059669',
    isDark: false,
    category: 'nature',
    emoji: '🌿',
    cssVars: {
      '--app-bg': '#ebf7f0',
      '--app-surface': '#f5fdf8',
      '--app-surface-hover': '#daf0e4',
      '--app-border': '#b8dcc8',
      '--app-text': '#0e2a1c',
      '--app-text-secondary': '#367a55',
      '--accent': '#059669',
    },
  }),
  normalize({
    id: 'deep-forest',
    name: 'ليل الغابة',
    description: 'أخضر غامق غني مع ظلال الليل. هدوء واحترافية.',
    colors: ['#34d399', '#10b981', '#0f2922'],
    previewColor: '#0a1f17',
    accent: '#34d399',
    isDark: true,
    category: 'nature',
    emoji: '🌲',
    cssVars: {
      '--app-bg': '#080f0c',
      '--app-surface': '#10201a',
      '--app-surface-hover': '#183028',
      '--app-border': '#204038',
      '--app-text': '#d0f0e0',
      '--app-text-secondary': '#60b88a',
      '--accent': '#34d399',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // جريء — Bold
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'crimson-dark',
    name: 'قرمزي مظلم',
    description: 'أحمر قرمزي عميق في وضع مظلم. قوة وتميّز.',
    colors: ['#f87171', '#ef4444', '#1c0a0a'],
    previewColor: '#170808',
    accent: '#f87171',
    isDark: true,
    category: 'bold',
    emoji: '🔥',
    cssVars: {
      '--app-bg': '#100606',
      '--app-surface': '#1c0c0c',
      '--app-surface-hover': '#2c1414',
      '--app-border': '#401818',
      '--app-text': '#f5d8d8',
      '--app-text-secondary': '#d07070',
      '--accent': '#f87171',
    },
  }),
  normalize({
    id: 'sunset-orange',
    name: 'غروب برتقالي',
    description: 'ألوان الغروب الدافئة. طاقة إيجابية وحيوية.',
    colors: ['#f97316', '#fb923c', '#fff7ed'],
    previewColor: '#fff7ed',
    accent: '#ea6c0c',
    isDark: false,
    category: 'bold',
    emoji: '🌅',
    cssVars: {
      '--app-bg': '#fef0e0',
      '--app-surface': '#fff8ef',
      '--app-surface-hover': '#fde8d0',
      '--app-border': '#f0d0a8',
      '--app-text': '#3a1e08',
      '--app-text-secondary': '#8a5a28',
      '--accent': '#ea6c0c',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // شركة — Corporate & Modern
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'corporate-slate',
    name: 'شركة رمادية',
    description: 'رمادي حديث أنيق للشركات الناشئة والتقنية.',
    colors: ['#6366f1', '#818cf8', '#eef2ff'],
    previewColor: '#eef2ff',
    accent: '#6366f1',
    isDark: false,
    category: 'corporate',
    emoji: '🏢',
    cssVars: {
      '--app-bg': '#eef2ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#e0e7ff',
      '--app-border': '#c7d2fe',
      '--app-text': '#1e1b4b',
      '--app-text-secondary': '#4338ca',
      '--accent': '#6366f1',
    },
  }),
  normalize({
    id: 'corporate-slate-dark',
    name: 'ليل الشركة',
    description: 'وضع مظلم أنيق للشركات التقنية الحديثة.',
    colors: ['#818cf8', '#6366f1', '#1e1b4b'],
    previewColor: '#1e1b4b',
    accent: '#818cf8',
    isDark: true,
    category: 'corporate',
    emoji: '💻',
    cssVars: {
      '--app-bg': '#0f0f1a',
      '--app-surface': '#1a1a2e',
      '--app-surface-hover': '#252542',
      '--app-border': '#363654',
      '--app-text': '#e0e7ff',
      '--app-text-secondary': '#818cf8',
      '--accent': '#818cf8',
    },
  }),
  normalize({
    id: 'modern-teal',
    name: 'تركواز عصري',
    description: 'تركواز حداثي نظيف للتطبيقات المالية.',
    colors: ['#14b8a6', '#2dd4bf', '#f0fdfa'],
    previewColor: '#f0fdfa',
    accent: '#0d9488',
    isDark: false,
    category: 'corporate',
    emoji: '🎯',
    cssVars: {
      '--app-bg': '#f0fdfa',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ccfbf1',
      '--app-border': '#99f6e4',
      '--app-text': '#042f2e',
      '--app-text-secondary': '#115e59',
      '--accent': '#0d9488',
    },
  }),
  normalize({
    id: 'modern-cyan',
    name: 'سيان حديث',
    description: 'أزرق سيان نابض بالحياة للتطبيقات الحيوية.',
    colors: ['#06b6d4', '#22d3ee', '#ecfeff'],
    previewColor: '#ecfeff',
    accent: '#0891b2',
    isDark: false,
    category: 'corporate',
    emoji: '💠',
    cssVars: {
      '--app-bg': '#ecfeff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#cffafe',
      '--app-border': '#a5f3fc',
      '--app-text': '#083344',
      '--app-text-secondary': '#155e75',
      '--accent': '#0891b2',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // ليلي — Night Themes
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'night-amethyst',
    name: 'ليلي ياقوتي',
    description: 'ياقوت أرجواني داكن مع بريق星光.',
    colors: ['#a855f7', '#c084fc', '#2e1065'],
    previewColor: '#2e1065',
    accent: '#a855f7',
    isDark: true,
    category: 'night',
    emoji: '✨',
    cssVars: {
      '--app-bg': '#0f0a1f',
      '--app-surface': '#1a1229',
      '--app-surface-hover': '#251a38',
      '--app-border': '#3d2a52',
      '--app-text': '#f3e8ff',
      '--app-text-secondary': '#c084fc',
      '--accent': '#a855f7',
    },
  }),
  normalize({
    id: 'night-sapphire',
    name: 'ليلي ياقوت أزرق',
    description: 'ياقوت أزرق داكن مع لمسات فيروزية.',
    colors: ['#38bdf8', '#7dd3fc', '#0c4a6e'],
    previewColor: '#0c4a6e',
    accent: '#38bdf8',
    isDark: true,
    category: 'night',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#071a2e',
      '--app-surface': '#0f2847',
      '--app-surface-hover': '#163660',
      '--app-border': '#1e4976',
      '--app-text': '#e0f2fe',
      '--app-text-secondary': '#7dd3fc',
      '--accent': '#38bdf8',
    },
  }),
  normalize({
    id: 'night-gold',
    name: 'ليل ذهبي',
    description: 'ذهب داكن مع لمسات برتقالية ليلية.',
    colors: ['#fbbf24', '#fcd34d', '#451a03'],
    previewColor: '#451a03',
    accent: '#fbbf24',
    isDark: true,
    category: 'night',
    emoji: '🌟',
    cssVars: {
      '--app-bg': '#1a1205',
      '--app-surface': '#2a1c08',
      '--app-surface-hover': '#3d2810',
      '--app-border': '#5c3d18',
      '--app-text': '#fef3c7',
      '--app-text-secondary': '#fbbf24',
      '--accent': '#fbbf24',
    },
  }),
  normalize({
    id: 'night-rose',
    name: 'ليلي وردي',
    description: 'وردي داكن أنيق مع تدرجات أرجوانية.',
    colors: ['#fb7185', '#fb923c', '#881337'],
    previewColor: '#881337',
    accent: '#fb7185',
    isDark: true,
    category: 'night',
    emoji: '🌹',
    cssVars: {
      '--app-bg': '#1a0812',
      '--app-surface': '#2d101c',
      '--app-surface-hover': '#401828',
      '--app-border': '#5c2036',
      '--app-text': '#ffe4e6',
      '--app-text-secondary': '#fb7185',
      '--accent': '#fb7185',
    },
  }),
];
