import type { ThemePreset } from '../types';
import { normalize } from './normalize';

export const PREMIUM_PRESETS: ThemePreset[] = [
  // ══════════════════════════════════════════════════════════════════════
  // باقات برو الاحترافية — Premium Pro
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'emerald-pro',
    name: 'زمردي احترافي',
    description: 'مزيج من ألوان الغابات الزمردية العميقة. هدوء وفخامة في كل وضع.',
    colors: ['#059669', '#10b981', '#ecfdf5'],
    previewColor: '#059669',
    accent: '#059669',
    isDark: false,
    category: 'premium',
    emoji: '🌿',
    light: {
      '--app-bg': '#f0fdf4',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dcfce7',
      '--app-border': '#bbf7d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    },
    dark: {
      '--app-bg': '#05140e',
      '--app-surface': '#0c241b',
      '--app-surface-hover': '#12382a',
      '--app-border': '#194a37',
      '--app-text': '#ecfdf5',
      '--app-text-secondary': '#6ee7b7',
      '--accent': '#10b981',
    },
  }),
  normalize({
    id: 'sapphire-pro',
    name: 'ياقوت أزرق احترافي',
    description: 'أزرق كحلي عميق مع لمسات فضية باردة. للمكاتب الرسمية والمؤسسات.',
    colors: ['#1e40af', '#3b82f6', '#eff6ff'],
    previewColor: '#1e40af',
    accent: '#1e40af',
    isDark: false,
    category: 'premium',
    emoji: '💎',
    light: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#1e40af',
    },
    dark: {
      '--app-bg': '#0a0f1e',
      '--app-surface': '#141b2d',
      '--app-surface-hover': '#1e293b',
      '--app-border': '#1e293b',
      '--app-text': '#e2e8f0',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#3b82f6',
    },
  }),
  normalize({
    id: 'amethyst-pro',
    name: 'أرجواني ملكي احترافي',
    description: 'أناقة اللافندر الفاخر مع تدرجات رويال. لمسة إبداعية متميزة.',
    colors: ['#6d28d9', '#8b5cf6', '#f5f3ff'],
    previewColor: '#6d28d9',
    accent: '#6d28d9',
    isDark: false,
    category: 'premium',
    emoji: '🔮',
    light: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#2e1065',
      '--app-text-secondary': '#6d28d9',
      '--accent': '#6d28d9',
    },
    dark: {
      '--app-bg': '#0f0a1f',
      '--app-surface': '#1a1229',
      '--app-surface-hover': '#251a38',
      '--app-border': '#3d2a52',
      '--app-text': '#f3e8ff',
      '--app-text-secondary': '#c084fc',
      '--accent': '#a855f7',
    },
  }),
  normalize({
    id: 'obsidian-pro',
    name: 'أوبسيديان فاخر',
    description: 'تباين عالٍ يجمع بين الفولاذ المصقول والأسود الفاخر. لمحبي الحداثة.',
    colors: ['#0f172a', '#334155', '#f8fafc'],
    previewColor: '#0f172a',
    accent: '#0f172a',
    isDark: false,
    category: 'premium',
    emoji: '🖤',
    light: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#cbd5e1',
      '--app-text': '#020617',
      '--app-text-secondary': '#475569',
      '--accent': '#0f172a',
    },
    dark: {
      '--app-bg': '#09090b',
      '--app-surface': '#121215',
      '--app-surface-hover': '#1c1c22',
      '--app-border': '#27272a',
      '--app-text': '#fafafa',
      '--app-text-secondary': '#a1a1aa',
      '--accent': '#ffffff',
    },
  }),
];
