import type { ThemePreset } from '../types';
import { normalize } from './normalize';

export const SPECIALTY_PRESETS: ThemePreset[] = [
  // ══════════════════════════════════════════════════════════════════════
  // موسمي — Seasonal
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'spring-pink',
    name: 'وردي ربيعي',
    description: 'وردي primaveral نابض بالحياة والأمل.',
    colors: ['#ec4899', '#f472b6', '#fdf2f8'],
    previewColor: '#fdf2f8',
    accent: '#db2777',
    isDark: false,
    category: 'seasonal',
    emoji: '🌸',
    cssVars: {
      '--app-bg': '#fdf2f8',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fce7f3',
      '--app-border': '#fbcfe8',
      '--app-text': '#831843',
      '--app-text-secondary': '#be185d',
      '--accent': '#db2777',
    },
  }),
  normalize({
    id: 'summer-cyan',
    name: 'سيان صيفي',
    description: 'أزرق صيفي منعش مع لمسات فيروزية.',
    colors: ['#06b6d4', '#22d3ee', '#ecfeff'],
    previewColor: '#ecfeff',
    accent: '#0891b2',
    isDark: false,
    category: 'seasonal',
    emoji: '☀️',
    cssVars: {
      '--app-bg': '#ecfeff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#cffafe',
      '--app-border': '#a5f3fc',
      '--app-text': '#083344',
      '--app-text-secondary': '#155e75',
      '--accent': '#0891b2',
    },
  }),
  normalize({
    id: 'autumn-orange',
    name: 'برتقالي خريفي',
    description: 'برتقالي دافئ بألوان أوراق الخريف.',
    colors: ['#ea580c', '#f97316', '#fff7ed'],
    previewColor: '#fff7ed',
    accent: '#c2410c',
    isDark: false,
    category: 'seasonal',
    emoji: '🍂',
    cssVars: {
      '--app-bg': '#fff7ed',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ffedd5',
      '--app-border': '#fed7aa',
      '--app-text': '#7c2d12',
      '--app-text-secondary': '#c2410c',
      '--accent': '#c2410c',
    },
  }),
  normalize({
    id: 'winter-blue',
    name: 'أزرق شتوي',
    description: 'أزرق بارد مع لمسات ثلجية.',
    colors: ['#3b82f6', '#60a5fa', '#eff6ff'],
    previewColor: '#eff6ff',
    accent: '#2563eb',
    isDark: false,
    category: 'seasonal',
    emoji: '❄️',
    cssVars: {
      '--app-bg': '#eff6ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dbeafe',
      '--app-border': '#bfdbfe',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#2563eb',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // فني — Artistic
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'artist-indigo',
    name: 'أنديغو فني',
    description: 'أنديغو عميق مع لمسات بنفسجية.',
    colors: ['#6366f1', '#818cf8', '#e0e7ff'],
    previewColor: '#e0e7ff',
    accent: '#4f46e5',
    isDark: false,
    category: 'artistic',
    emoji: '🎨',
    cssVars: {
      '--app-bg': '#e0e7ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#c7d2fe',
      '--app-border': '#a5b4fc',
      '--app-text': '#312e81',
      '--app-text-secondary': '#4f46e5',
      '--accent': '#4f46e5',
    },
  }),
  normalize({
    id: 'artist-lavender',
    name: 'لافندر فني',
    description: 'خزامي ناعم مع لمسات فيروزية.',
    colors: ['#a78bfa', '#c4b5fd', '#f5f3ff'],
    previewColor: '#f5f3ff',
    accent: '#8b5cf6',
    isDark: false,
    category: 'artistic',
    emoji: '🖌️',
    cssVars: {
      '--app-bg': '#f5f3ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#ede9fe',
      '--app-border': '#ddd6fe',
      '--app-text': '#4c1d95',
      '--app-text-secondary': '#7c3aed',
      '--accent': '#8b5cf6',
    },
  }),
  normalize({
    id: 'minimal-gray',
    name: 'رمادي بسيط',
    description: 'بسيط ونظيف مع لمسات أرجوانية خفيفة.',
    colors: ['#a1a1aa', '#71717a', '#fafafa'],
    previewColor: '#fafafa',
    accent: '#71717a',
    isDark: false,
    category: 'artistic',
    emoji: '⬜',
    cssVars: {
      '--app-bg': '#fafafa',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f4f4f5',
      '--app-border': '#e4e4e7',
      '--app-text': '#27272a',
      '--app-text-secondary': '#52525b',
      '--accent': '#71717a',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // قطاعي — Industry
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'health-medical',
    name: 'طبي صحي',
    description: 'أخضر طبي هادئ للمنشآت الصحية.',
    colors: ['#10b981', '#34d399', '#ecfdf5'],
    previewColor: '#ecfdf5',
    accent: '#059669',
    isDark: false,
    category: 'industry',
    emoji: '🏥',
    cssVars: {
      '--app-bg': '#ecfdf5',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#d1fae5',
      '--app-border': '#a7f3d0',
      '--app-text': '#064e3b',
      '--app-text-secondary': '#047857',
      '--accent': '#059669',
    },
  }),
  normalize({
    id: 'food-restaurant',
    name: 'مطاعم وطعام',
    description: 'برتقالي دافئ للمطاعم والوجبات.',
    colors: ['#f59e0b', '#fbbf24', '#fffbeb'],
    previewColor: '#fffbeb',
    accent: '#d97706',
    isDark: false,
    category: 'industry',
    emoji: '🍽️',
    cssVars: {
      '--app-bg': '#fffbeb',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fef3c7',
      '--app-border': '#fde68a',
      '--app-text': '#78350f',
      '--app-text-secondary': '#b45309',
      '--accent': '#d97706',
    },
  }),
  normalize({
    id: 'education-school',
    name: 'تعليم ومدرسة',
    description: 'أزرق تعليمي هادئ للمدارس.',
    colors: ['#3b82f6', '#60a5fa', '#eff6ff'],
    previewColor: '#eff6ff',
    accent: '#2563eb',
    isDark: false,
    category: 'industry',
    emoji: '📚',
    cssVars: {
      '--app-bg': '#eff6ff',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#dbeafe',
      '--app-border': '#bfdbfe',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#2563eb',
    },
  }),
  normalize({
    id: 'automotive-car',
    name: 'سيارات و قطع غيار',
    description: 'أزرق داكن احترافي لصناعة السيارات.',
    colors: ['#1d4ed8', '#3b82f6', '#dbeafe'],
    previewColor: '#dbeafe',
    accent: '#1e40af',
    isDark: false,
    category: 'automotive',
    emoji: '🚗',
    cssVars: {
      '--app-bg': '#dbeafe',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#bfdbfe',
      '--app-border': '#93c5fd',
      '--app-text': '#1e3a8a',
      '--app-text-secondary': '#1d4ed8',
      '--accent': '#1e40af',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // زجاجي — Glass
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'crystal-glass',
    name: 'كريستال زجاجي',
    description: 'شفافية ناصعة مع بلور ناعم. مظهر عصري وخفيف جداً.',
    colors: ['#ffffff', '#f0f9ff', '#e0f2fe'],
    previewColor: '#ffffff',
    accent: '#3b82f6',
    isDark: false,
    category: 'glass',
    emoji: '💎',
    cssVars: {
      '--app-bg': '#f8fafc',
      '--app-surface': 'rgba(255, 255, 255, 0.7)',
      '--app-surface-hover': 'rgba(255, 255, 255, 0.9)',
      '--app-border': 'rgba(255, 255, 255, 0.5)',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#3b82f6',
    },
  }),
  normalize({
    id: 'frosted-obsidian',
    name: 'أوبسيديان مثلج',
    description: 'زجاج داكن مع تأثير الثلج. فخامة وهدوء في الوضع الليلي.',
    colors: ['#0f172a', '#1e293b', '#334155'],
    previewColor: '#0f172a',
    accent: '#818cf8',
    isDark: true,
    category: 'glass',
    emoji: '🌌',
    cssVars: {
      '--app-bg': '#020617',
      '--app-surface': 'rgba(15, 23, 42, 0.7)',
      '--app-surface-hover': 'rgba(30, 41, 59, 0.8)',
      '--app-border': 'rgba(255, 255, 255, 0.1)',
      '--app-text': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#818cf8',
    },
  }),
  normalize({
    id: 'aurora-glass',
    name: 'أورورا زجاجي',
    description: 'تدرجات ألوان الشفق القطبي خلف زجاج شفاف. إبداع وحيوية.',
    colors: ['#4f46e5', '#ec4899', '#06b6d4'],
    previewColor: '#4f46e5',
    accent: '#6366f1',
    isDark: false,
    category: 'glass',
    emoji: '🌈',
    cssVars: {
      '--app-bg': 'linear-gradient(135deg, #f5f3ff 0%, #fdf2f8 50%, #ecfeff 100%)',
      '--app-surface': 'rgba(255, 255, 255, 0.6)',
      '--app-surface-hover': 'rgba(255, 255, 255, 0.8)',
      '--app-border': 'rgba(255, 255, 255, 0.4)',
      '--app-text': '#1e1b4b',
      '--app-text-secondary': '#4338ca',
      '--accent': '#6366f1',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // بينتو — Bento
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'bento-pro',
    name: 'بينتو احترافي',
    description: 'تقسيمات هندسية دقيقة مع تباين عالي. مثالي للوحات البيانات المعقدة.',
    colors: ['#0f172a', '#f1f5f9', '#3b82f6'],
    previewColor: '#f1f5f9',
    accent: '#2563eb',
    isDark: false,
    category: 'bento',
    emoji: '📊',
    cssVars: {
      '--app-bg': '#f1f5f9',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f8fafc',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#64748b',
      '--accent': '#2563eb',
    },
  }),
  // ══════════════════════════════════════════════════════════════════════
  // قطع غيار — Automotive
  // ══════════════════════════════════════════════════════════════════════
  normalize({
    id: 'racing-red',
    name: 'أحمر سباق',
    description: 'ألوان سباقات السيارات الحمراء الجريئة. طاقة وحماس للمخازن وقطع الغيار.',
    colors: ['#dc2626', '#ef4444', '#fef2f2'],
    previewColor: '#dc2626',
    accent: '#dc2626',
    isDark: false,
    category: 'automotive',
    emoji: '🏎️',
    light: {
      '--app-bg': '#fef2f2',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#fee2e2',
      '--app-border': '#fecaca',
      '--app-text': '#450a0a',
      '--app-text-secondary': '#991b1b',
      '--accent': '#dc2626',
    },
    dark: {
      '--app-bg': '#1a0000',
      '--app-surface': '#2d0000',
      '--app-surface-hover': '#3d0000',
      '--app-border': '#4d1111',
      '--app-text': '#fecaca',
      '--app-text-secondary': '#f87171',
      '--accent': '#ef4444',
    },
  }),
  normalize({
    id: 'garage-dark',
    name: 'كراج ليلي',
    description: 'أجواء الكراج الليلي الداكنة مع لمسات معدنية. مثالية للعمل الليلي في المخازن.',
    colors: ['#334155', '#64748b', '#0f172a'],
    previewColor: '#334155',
    accent: '#f59e0b',
    isDark: true,
    category: 'automotive',
    emoji: '🔧',
    light: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#e2e8f0',
      '--app-text': '#0f172a',
      '--app-text-secondary': '#475569',
      '--accent': '#f59e0b',
    },
    dark: {
      '--app-bg': '#0f172a',
      '--app-surface': '#1e293b',
      '--app-surface-hover': '#334155',
      '--app-border': '#334155',
      '--app-text': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--accent': '#f59e0b',
    },
  }),
  normalize({
    id: 'carbon-fiber',
    name: 'ألياف كربونية',
    description: 'نمط ألياف الكربون الأسود مع لمسات زرقاء تقنية. تصميم رياضي حديث.',
    colors: ['#1e293b', '#3b82f6', '#0f172a'],
    previewColor: '#1e293b',
    accent: '#3b82f6',
    isDark: true,
    category: 'automotive',
    emoji: '⚡',
    light: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-hover': '#f1f5f9',
      '--app-border': '#cbd5e1',
      '--app-text': '#1e293b',
      '--app-text-secondary': '#475569',
      '--accent': '#3b82f6',
    },
    dark: {
      '--app-bg': '#0a0f1a',
      '--app-surface': '#141c2e',
      '--app-surface-hover': '#1e293b',
      '--app-border': '#1e3a5f',
      '--app-text': '#e2e8f0',
      '--app-text-secondary': '#64748b',
      '--accent': '#3b82f6',
    },
  }),
];
